### ISSUE TITLE
No Sign up feature

### ISSUE THREAD

**Issue by amenabe22** [docusealco/docuseal#101]
Can't access sign up or sign_up route that you had on the cloud version which pricing tier includes the sign up capability to manage more businessses

**Comment by AlexandrToorchyn** [comment]
@amenabe22 Multitenant capabilities are available at DocuSeal cloud - open source verison contains them but they are not documented and it might be hard to set everything up. The goal of open source is to provide a simple signing solution for small companies and individuals.

But maybe you don't even need a multitenant docuseal? At DocuSeal we have embeddable form builder so you can have multiple companies create their own documents under your account: https://console.docuseal.co/embedding/builder

Let me know if that's something you're looking for
