### ISSUE TITLE
Document signature feature not loading on page

### ISSUE THREAD

**Issue by rodolphoarruda** [docusealco/docuseal#103]
When I click the link sent in the signature request email, the browser launches just the original document and no signature features, so I can't pass that step in the process. 

![DocuSeal-Open-Source-Document-Filling-and-Signing](https://github.com/docusealco/docuseal/assets/23284944/3151e63c-7726-430c-8dc5-1879d9ad4c0e)

**Comment by AlexandrToorchyn** [comment]
@rodolphoarruda could you please check your browser console for JS errors? there must be something wrong with your template or browser causing an error so that the form is not rendered

**Comment by rodolphoarruda** [comment]
`TypeError: Jt[Xt] is undefined
    t i18n.js:205
    ti form.vue:78
    J runtime-core.esm-bundler.js:816
    effect runtime-core.esm-bundler.js:5701
    run reactivity.esm-bundler.js:178
    update runtime-core.esm-bundler.js:5814
    B runtime-core.esm-bundler.js:5822
    $ runtime-core.esm-bundler.js:5613
    D runtime-core.esm-bundler.js:5565
    b runtime-core.esm-bundler.js:5040
    se runtime-core.esm-bundler.js:6332
    mount runtime-core.esm-bundler.js:3824
    mount runtime-dom.esm-bundler.js:1431
    connectedCallback form.js:24
    306 form.js:7
    Webpack 5
runtime-core.esm-bundler.js:226:12
InstallTrigger está obsoleto e será removido no futuro. commons.js:2:1416762
`

**Comment by AlexandrToorchyn** [comment]
@rodolphoarruda thanks for reporting this - it has been fixed in the latest release
