### ISSUE TITLE
`block in ffi_lib': Could not open library 'libglib-2.0-0.dll'

### ISSUE THREAD

**Issue by zhushuqi123** [docusealco/docuseal#104]
C:/Users/admin/.local/share/gem/ruby/3.2.0/gems/ffi-1.15.5/lib/ffi/library.rb:145:in `block in ffi_lib': Could not open library 'libglib-2.0-0.dll':  (LoadError)
        from C:/Users/admin/.local/share/gem/ruby/3.2.0/gems/ffi-1.15.5/lib/ffi/library.rb:99:in `map'
        from C:/Users/admin/.local/share/gem/ruby/3.2.0/gems/ffi-1.15.5/lib/ffi/library.rb:99:in `ffi_lib'
        from C:/Users/admin/.local/share/gem/ruby/3.2.0/gems/ruby-vips-2.1.4/lib/vips.rb:45:in `<module:GLib>'
        from C:/Users/admin/.local/share/gem/ruby/3.2.0/gems/ruby-vips-2.1.4/lib/vips.rb:36:in `<main>'
        from <internal:D:/Ruby32-x64/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:38:in `require'
        from <internal:D:/Ruby32-x64/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:38:in `require'
        from C:/Users/admin/.local/share/gem/ruby/3.2.0/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
        from C:/Users/admin/.local/share/gem/ruby/3.2.0/gems/ruby-vips-2.1.4/lib/ruby-vips.rb:1:in `<main>'
        from <internal:D:/Ruby32-x64/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:38:in `require'
        from <internal:D:/Ruby32-x64/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:38:in `require'

Why can't I find this dll?

**Comment by AlexandrToorchyn** [comment]
@zhushuqi123 Running ruby on windows is hard, It's recommended to use DocuSeal in docker instead.
