### ISSUE TITLE
error un db startup

### ISSUE THREAD

**Issue by maaper** [docusealco/docuseal#108]
Hello this morning I found my de service of docuseal down. 
When trying to repulo the image from my synology, I find this error.

![IMG_0731](https://github.com/docusealco/docuseal/assets/56989894/de4abc0a-d8e3-4fbb-9485-08267585bb8d)

Can someone help me to fixit or give me a clue on how to doit?
I have the service off and there is a lot of people calling me to fill the forms.

Thanks in advance.

**Comment by maaper** [comment]
When trying to start the db docker I get thi error:

```
PostgreSQL Database directory appears to contain a database; Skipping initialization
2023-09-17 08:19:06.522 UTC [1] FATAL:  database files are incompatible with server
2023-09-17 08:19:06.522 UTC [1] DETAIL:  The data directory was initialized by PostgreSQL version 15, which is not compatible with this version 16.0 (Debian 16.0-1.pgdg120+1).
PostgreSQL Database directory appears to contain a database; Skipping initialization
2023-09-17 08:30:20.615 UTC [1] FATAL:  database files are incompatible with server
2023-09-17 08:30:20.615 UTC [1] DETAIL:  The data directory was initialized by PostgreSQL version 15, which is not compatible with this version 16.0 (Debian 16.0-1.pgdg120+1).
PostgreSQL Database directory appears to contain a database; Skipping initialization
2023-09-17 08:30:36.158 UTC [1] FATAL:  database files are incompatible with server
2023-09-17 08:30:36.158 UTC [1] DETAIL:  The data directory was initialized by PostgreSQL version 15, which is not compatible with this version 16.0 (Debian 16.0-1.pgdg120+1).
```

Is there any update on docuseal that makes it not compatible with my NAS server?

**Comment by AlexandrToorchyn** [comment]
Last week Postgresql 16 has been released.
And so on docker hub Postgresql 15 has been pushed as the postgresql:latest tag.
Seems like your env is not compatible with Postgresql 15
Try to update your docker-compose yaml file and explicitry specify postgresql 14 there:
Replace postgres:latest with postgres:14
@mapper

**Comment by maaper** [comment]
And this is my actual YMAL file configuration:

```
version: '3.9'
services:
  docuseal:
    image: docuseal/docuseal:latest
    container_name: DocuSeal
    ports:
      - 3766:3000
    volumes:
      - /volume1/docker/docuseal:/data:rw
    environment:
      FORCE_SSL: true
      HOST: https://mycurrenthost
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/docuseal
    depends_on:
      postgres:
        condition: service_healthy
        
  postgres:
    image: postgres
    container_name: DocuSeal-DB
    mem_limit: 256m
    cpu_shares: 768
    volumes:
      - /volume1/docker/docuseal/db:/var/lib/postgresql/data:rw
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: docuseal
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
```

Where to specify the version?

**Comment by AlexandrToorchyn** [comment]
image: postgres - replace it with image: postgres:14

**Comment by maaper** [comment]
With that I get this error:

```
PostgreSQL Database directory appears to contain a database; Skipping initialization
2023-09-17 08:40:42.347 UTC [1] FATAL:  database files are incompatible with server
2023-09-17 08:40:42.347 UTC [1] DETAIL:  The data directory was initialized by PostgreSQL version 15, which is not compatible with this version 14.9 (Debian 14.9-1.pgdg120+1).
PostgreSQL Database directory appears to contain a database; Skipping initialization
2023-09-17 08:41:31.445 UTC [1] FATAL:  database files are incompatible with server
2023-09-17 08:41:31.445 UTC [1] DETAIL:  The data directory was initialized by PostgreSQL version 15, which is not compatible with this version 14.9 (Debian 14.9-1.pgdg120+1).
PostgreSQL Database directory appears to contain a database; Skipping initialization
2023-09-17 08:41:44.258 UTC [1] FATAL:  database files are incompatible with server
2023-09-17 08:41:44.258 UTC [1] DETAIL:  The data directory was initialized by PostgreSQL version 15, which is not compatible with this version 14.9 (Debian 14.9-1.pgdg120+1).
```

**Comment by maaper** [comment]
It’s not clear to me, who is on version 15, my system or docusel?
What version of PostgreSQL did docuseal needs?

**Comment by AlexandrToorchyn** [comment]
oh, actually change it to postgres:15 from postgres:14
it should fix the error

**Comment by maaper** [comment]
The system is up and running ok.
MANY THANKS for your quick support, you save me de day! 👍 

Remember i’m available to work in the project when you start with the translation to Spanish. (Al ready sent an email).

Thanks!

**Comment by maaper** [comment]
Thank for the quick support. 
The Postgress version should be 15. Docuseal its not currently working with 16.

**Comment by maaper** [comment]
Thank for the quick support.
The Postgress version should be 15. Docuseal its not currently working with 16.

**Comment by AlexandrToorchyn** [comment]
Postgresql version is not binded to DocuSeal app in any way, so this errors is more related to PG and docker env.

Here is what happened:
Your postgresql database was initialized with postgresql 15 a couple of months ago.
Now when pg 16 came out - you automatically updated your container to pg 16 (latest tag).
But since your pg database was initialized with version 15 - pg throws an error when trying to run your db on the newest version.

We probably need to hardcode pg version in docker-compose file to avoid this issue in the future for people that auto update containers.
I just wanted to clarify that Docuseal it working perfectly with postgresql 16 when the data folder is also initialize with pg 16 :).

**Comment by maaper** [comment]
Thanks @AlexandrToorchyn,

So if I’m properly understand, the issue is that my current db was created on 15-pg and now I keep tied to that version even if the PG is updated to 16-pg. I suppose there is no way to update my current installation to work with 16 because I have information with previous version.

I got the point that is not a docuseal issue, it’s because my previous information was already built with a non compatible version with actual pg16.

It’s my understanding ok?

**Comment by AlexandrToorchyn** [comment]
yeah right - your postgresql data folder has been created with 15 and so it can work with only pg 15 docker container image.

but this doesn't mean that you're tied to pg 15 forever - it's possible to upgrade your data folder to make it compatible with pg 16 format:
https://www.postgresql.org/docs/current/pgupgrade.html
but that might be not easy to do and requires backups - so you'd probably prefer to stay with pg 15 :)

**Comment by maaper** [comment]
In fact yes. Now there is one form collecting users information, so it’s not the best moment to make any update. 
I will mark it as pending work and try to update in the near future. The good is that I always have the option of fully backup the folder of the docuseal docker. 👍

Again, thanks for your quick response.
