### ISSUE TITLE
Feature Suggestions

### ISSUE THREAD

**Issue by ErminMerdanovic** [docusealco/docuseal#115]
Hello! Before I begin, I stumbled upon this amazing software randomly and I wanted to express my gratitude to the developers. I didn't know I would need this tool, but it's been a great asset for signing documents.

Here are a few suggestions I have:

1. It would be fantastic to have a German translation, and I'm willing to assist with achieving this.
2. Some minor tweaks to the CSS appearance to have somthing like global color variables for easy customization.
3. Additionally, for self-hosted users interested in pro/enterprise features (like whitelabeling), perhaps consider introducing a smaller annual fee of around 30€. I've noticed similar pricing schemes in different open-source projects (such as Invoice Ninja), and I believe this could be a valuable option for those who want to host it themselves.

**Comment by AlexandrToorchyn** [comment]
Hi @ErminMerdanovic thanks for the feedback!

1. We will start working on translation this year
2. We don't have plans to add global css variable for style customisations by users
3. OSS has a lot of features for personal use and we already have an affordable Pro hosted for $8/mo
