### ISSUE TITLE
`require': Could not load the 'mysql' Active Record adapter.

### ISSUE THREAD

**Issue by PIKACHUIM** [docusealco/docuseal#118]
I want use mysql, however：

DATABASE_URL = mysql://username:password@172.17.0.1:3306/docuseals

`require': Could not load the 'mysql' Active Record adapter. Ensure that the adapter is spelled correctly in config/database.yml and that you've added the necessary adapter gem to your Gemfile. (LoadError)

Thank you!

**Comment by AlexandrToorchyn** [comment]
use mysql2:// in the URL to fix the issue

**Comment by PIKACHUIM** [comment]
Thank you for your timely and patient answer. I tried to modify it to mysql2, but there was an error as follows:

Mysql2::Error: BLOB/TEXT column 'uuid' used in key specification wit                                                                                  hout a key length (ActiveRecord::StatementInvalid)

**Comment by AlexandrToorchyn** [comment]
It has been fixed in the latest version

**Comment by PIKACHUIM** [comment]
Thank you for your kind support!
