### ISSUE TITLE
[Feature Request] default values for text fields

### ISSUE THREAD

**Issue by fotofiete** [docusealco/docuseal#119]
Hi,
we really like working with docuseal in our org! One use case we have is to sign a photo declaration for events. Therefore we have a blueprint with fields for the events name, the date, the name and the signature.
When starting a new event we clone this blueprint and invite all the events guests. This has the downside, that the user has to fill in event and date on his own which might lead to heaps of different values. Here it would be great to be able to either add a standard text (without a form field) holding e.g. the events name or to be able to provide a default value for a text field...
Other possibility of course is to create a new form with a new PDF holding these values but then you have to recreate all the other input fields...
(Or do I missunderstand something basically? :see_no_evil: )

Thanks for your work! :smile:

**Comment by AlexandrToorchyn** [comment]
@fotofiete there are two ways to improve this workflow:
- You can try to add yourself as the first submitter of the form - you'll
fill the event name and date for them, and once it's done the form will be
passed to them with those fields already filled and displayed in the form
where they just need to put their signature.
- You can create a new PDF with those fields already pre-filled - and then
you can just replace the existing document file in the cloned template form
- all fields should remain in their place and you don't need to redraw them
(replace button appears if you hover on the page preview on the left)

Let me know if anything from the above solves your problem

**Comment by fotofiete** [comment]
@AlexandrToorchyn ah cool, thanks for your reply – especially the way to exchange the PDF file sounds very promising! :)

for me that's fine as a solution – it's up to you to leave this ticket open to still implement a possibility for read-only fields or default values (which both would be cool, too!) or to close it as resolved... :smile:

**Comment by omohokcoj** [comment]
@fotofiete default values have been added in the 1.2.6 version:
Default values can also accept embedded variables: {name}, {role}, {date}, {time}, {email}, {phone}
![image](https://github.com/docusealco/docuseal/assets/5418788/18e3358f-dc4a-4493-a054-028d35d38106)
