### ISSUE TITLE
On-prem install with "Console" links

### ISSUE THREAD

**Issue by mike-choi-solsim** [docusealco/docuseal#120]
Just getting started with docuseal. My question is what is the purpose of the Console links in the on-prem install? Was this intentional or a bug because I am very confused on its purpose.

**Comment by AlexandrToorchyn** [comment]
console link has been added for Pro and Enterprise On-premise users to
manage their license and monitor the usage
you can disregard it if you just use the basic OSS and fee Docuseal

**Comment by AlexandrToorchyn** [comment]
@mike-choi-solsim 
>it takes you to the Cloud hosted version of docuseal and not back to the on-prem version.

thats thats a good point - i see how this can be confusing. will try find some way to redirect back to the self-hsoted app. closing the issue since it's related to DocuSeal Console which is not a part of the OSS project.

**Comment by mariushosting** [comment]
> @mike-choi-solsim
> 
> > it takes you to the Cloud hosted version of docuseal and not back to the on-prem version.
> 
> thats thats a good point - i see how this can be confusing. will try find some way to redirect back to the self-hsoted app. closing the issue since it's related to DocuSeal Console which is not a part of the OSS project.

Very disappointed about this issue that intentionally misleading users. @AlexandrToorchyn
