### ISSUE TITLE
Data not showing in Filled out Forms

### ISSUE THREAD

**Issue by csayre** [docusealco/docuseal#121]
Hello, 

I believe I have discovered a bug, but I am not sure why this is happening. It does not seem to happen with every submission. Here is what I am seeing. I have a fairly long application that has 150 + fields that need to be filled out. I'd say 90% of the fields are required, but it seems like the application did one of the following things:
a) did not collect the data
b) did not store the data
c) or is not displaying the data 

I am not sure how to proceed to begin to troubleshoot this. 

On some of the applications the data is collected and displayed correctly, but on others it's just like it's not there. Please let me know if there is any data that I can provide. I will have to sanitize a lot of the data, but I will share what I can.

**Comment by omohokcoj** [comment]
@csayre could you please provide some logs from the app in docker and from the browser console when it fails to collect all the filled out data?

**Comment by csayre** [comment]
@omohokcoj I can try. I can send the docker logs from when it has happened if that would be helpful. I have not tried to replicate this issue yet. I am having people fill out an application that has 100's of fields. Its a bit tedious to test that over and over again. Do you know of a way to automate entry to those fields? I was thinking of some type of script that can run and just make a lot of submissions over and over again.

**Comment by omohokcoj** [comment]
@csayre is has been a while since this issue reported, unfortunately we were not able to reproduce it.
Maybe try to update to the latest version - it could have been fixed along with some other changes we regular add.
Please feel free to reopen if the issue persists in the latest version
