### ISSUE TITLE
[Feature Request] Permanently delete documents

### ISSUE THREAD

**Issue by nichu42** [docusealco/docuseal#122]
Hi there,

I'll keep this short:
I'd like to have the possibility to permanently delete documents from the archive.

Thanks for your consideration.

**Comment by omohokcoj** [comment]
@nichu42 the ability to permanently remove documents has been released in the 1.2.5 version

**Comment by nichu42** [comment]
Thanks! Do you know when this will be rolled out to docuseal.eu?

**Comment by omohokcoj** [comment]
@nichu42 currently it's available only in the docker self-hosted version.
will make it available in the cloud next week - reopening the issue until it's resolved :)

**Comment by omohokcoj** [comment]
@nichu42 permanently delete button is not available in the docuseal.eu Cloud
Apologize for the delay :)
