### ISSUE TITLE
help！

### ISSUE THREAD

**Issue by wintsa123** [docusealco/docuseal#126]
I am confused, I have not looked closely at the code, but I would like to know specific information about e-signatures. The official website states three rates。

1. is it free to deploy the service here source code open source yourself? 
2. And who has credibility on the signature after you sign it yourself? 
3. Is a similar ssl certificate organization?

**Comment by AlexandrToorchyn** [comment]
@wintsa123 
1. There is a docker image to host it yourself and the code is open-source and licensed under AGPLv3.
2. For the majority of use cases the documents signed via self-hosted DocuSeal are valid and legally binding but it depends on the type of your transactions and your local regulations.
3. Self-hosted DocuSeal generates self-signed X.509 certificate to seal documents - the same format is used by SSL protocol. You can sign documents with SSL certificate but it doesn't make much sense from the legal pov

**Comment by wintsa123** [comment]
> @wintsa123
> 
> 1. 有一个 docker 镜像可以自己托管它，代码是开源的，并在 AGPLv3 下获得许可。
> 2. 对于大多数用例，通过自托管 DocuSeal 签署的文件是有效且具有法律约束力的，但这取决于您的交易类型和当地法规。
> 3. 自托管 DocuSeal 生成自签名的 X.509 证书来密封文档 - SSL 协议使用相同的格式。您可以使用SSL证书签署文档，但从法律角度来看没有多大意义

我感到困惑，签名文件应该上传到相关机构才有法律效力，如果我自己签名似乎是没多大意义，但上传到相关机构这一步，在中国，好像只有个别公司才有资格上传证书到相关的机构
