### ISSUE TITLE
Right to Left Writing Direction

### ISSUE THREAD

**Issue by NoTellingyou** [docusealco/docuseal#127]
When editing the document itself everything works fine but after downloading it spells everything backwards.

**Comment by AlexandrToorchyn** [comment]
thanks @NoTellingyou, that's a known issue - right to left writing is not
supported yet. We're hoping to add it soon, stay tuned!

**Comment by ShlomiPorush** [comment]
Hi, Any update on this?

**Comment by omohokcoj** [comment]
@ShlomiPorush @NoTellingyou Right-to-left writing support has been added in the 1.3.7 release.
Please reopen if you find any issues with the RTL support
