### ISSUE TITLE
Configuration Documentation

### ISSUE THREAD

**Issue by PurpleBabar** [docusealco/docuseal#128]
Hi Guys,

Thanks for docuseal, the product is really cool :) 

I was wondering if there was some extended documentation about how you could configure the tool with env variables ?

I'm trying to make it work with S3 in environment variables but can't seem to figure it out (configuration does not appear in the UI and the disk option to save files seems to be selected) :/

It seems to be working with SMTP but when it's configured via environment variables I can't see the Email tab in the settings :/
Also, is there a way to configure send from adress from env variables ?

I'd be happy to help on these subject if needed :)
I don't know if all these questions should be here, but i'd be happy to relocate them elsewhere if needed :)

Cheerz
PurpleBabar

**Comment by omohokcoj** [comment]
@PurpleBabar you can try those variables for aws S3
S3_ATTACHMENTS_BUCKET
AWS_ACCESS_KEY_ID
AWS_SECRET_ACCESS_KEY
AWS_REGION

They can be found here:
https://github.com/docusealco/docuseal/blob/master/config/storage.yml#L8

Let me know if works :)

**Comment by avatar1024** [comment]
I would also agree that the documentation is a bit thin... I am personally puzzled for example on what are the tags that can be sued to customise email notifications. I can see the some tags in the default email template but I don't know what are the other tags available.

**Comment by omohokcoj** [comment]
@PurpleBabar a list of environment variables has been added to the docs:
https://www.docuseal.co/docs/configuring-docuseal-via-environment-variables

**Comment by omohokcoj** [comment]
@avatar1024 thanks for the feedback we will add the list of available email body variables to display in the the  settings UI 
closing the ticket since its not related to the original questions regarding the ENV variables.
