### ISSUE TITLE
[BUG] The date format will change automatically.

### ISSUE THREAD

**Issue by GXY2017** [docusealco/docuseal#132]
In the DATE field, after selecting the date from the calendar, the display format is not MM-DD-YYYY, but falls to format like 'DECEMBER-23-2023'.

It is suggested to modify so that the final displayed field is consistent with the date format required.

At the same time, it is suggested to add different date format choices in the date field to meet the requirements of different display effects.

Thank you very much

**Comment by maaper** [comment]
> In the DATE field, after selecting the date from the calendar, the display format is not MM-DD-YYYY, but falls to format like 'DECEMBER-23-2023'.
> 
> It is suggested to modify so that the final displayed field is consistent with the date format required.
> 
> At the same time, it is suggested to add different date format choices in the date field to meet the requirements of different display effects.
> 
> Thank you very much

Absolutely supporting that petition.

**Comment by avatar1024** [comment]
Would be really great to be able to customise the date format as currently it seems a bit random what actually appears in the document.

**Comment by wrigjz** [comment]
We find an issue where on the website it formats as we would like say '11 December 2023' when you view the file but when you download it it formats as 11/12/2023 which we can not use. Can it be fixed so allow the 11 December 2023 to be on the actual downloaded PDF. This was from testing with the self-hosted Docker.

**Comment by omohokcoj** [comment]
@GXY2017 @maaper now it's possible to set date forma per date field and this specified format will be used everywhere in the document:
![image](https://github.com/docusealco/docuseal/assets/5418788/2bc38d57-fa69-4909-89cb-b74c419f9c79)

Let me know if it solves the issue

**Comment by wrigjz** [comment]
Wow - that is just what we wanted to see, thanks.

**Comment by omohokcoj** [comment]
Closing the issue since the date format option has been added to the date field.
Please reopen in case you face any issuers with the date format
