### ISSUE TITLE
SMTP error with GMX provider.

### ISSUE THREAD

**Issue by GauthierCrp** [docusealco/docuseal#134]
Hello Everyone,

I'm trying to setup Docuseal behing NginxProxyManager, with SSL certificate by LetsEncrypt. All the application is working like a charm, in Https, with no SSL error.
When I try to setup the SMTP (crucial for signing purpose), I facing an error and no email can be sent from th server : 

![image](https://github.com/docusealco/docuseal/assets/30144651/e2594529-6f4c-4ac5-9033-412cfb3383a8)

I'm using GMX provider, I have activated the SMTP protocol on my account and the same configuration work on my Calibre-Web serveur.

![image](https://github.com/docusealco/docuseal/assets/30144651/f2bc8ab5-4001-4cf9-a749-4785306bd802)

Could you please help me to find what is wrong with this ?

Thank you in advance,
Best Regards

**Comment by dgarcia-lwolf** [comment]
@GauthierCrp it looks like the SSL port is set incorrectly, check here: https://bobbyhadz.com/blog/ssl-ssl-error-ssl-wrong-version-number#:~:text=The%20Python%20%22ssl.-,SSLError%3A%20%5BSSL%3A%20WRONG_VERSION_NUMBER%5D%20wrong%20version%20number%20(_ssl,of%20how%20the%20error%20occurs.

**Comment by GauthierCrp** [comment]
Hello @dgarcia-lwolf,

Thank you for your help.
I don't really understand why, but it's working. I switched from port 587 to 465 and the error is gone.

Best Regards,
Have a pleasant day.
