### ISSUE TITLE
FileDropZone not working

### ISSUE THREAD

**Issue by ekadin-mtc** [docusealco/docuseal#136]
I added a File field to my form, but nothing happens when I try using it.

**Comment by omohokcoj** [comment]
@ekadin-mtc thanks for reporting this. Looks like it was some weird vue bug that appears randomly (i was not able to constantly reproduce it)
https://github.com/docusealco/docuseal/commit/a42ae0b39e7d7ec8f590b95b212258ebab4d828f - I added this fix to ensure that the files array is always defined - it will be released in the next version.

**Comment by ekadin-mtc** [comment]
@omohokcoj Thanks for the quick fix! Looking forward to the next release :)

**Comment by omohokcoj** [comment]
@ekadin-mtc a new version has been released on Monday - the attachments step should work well there.
Please reopen if the issue still persists in the new version

**Comment by ekadin-mtc** [comment]
Indeed, it works now! Thanks, and keep up the great work!
