### ISSUE TITLE
Nokogiri ERROR

### ISSUE THREAD

**Issue by maaper** [docusealco/docuseal#138]
Hi all,
I’m receiving this error and my docker installation goes to exited. 

Nokogiri was built against libxml version 2.11.5, but has dynamically loaded 2.11.4

can someone help me to understand the possible root cause and possible solutions?
Thanks in advance!

**Comment by omohokcoj** [comment]
@maaper  it's not an error but a warning - the app should work perfectly fine with it :)

**Comment by maaper** [comment]
The thing is that the app is existing after restart.

**Comment by maaper** [comment]
I have just do a repull of the image and seems to be solve whatever was causing the issue. 

Now I remember that yesterday my server stopped suddenly due to an electrical issue. That abnormal shutdown can be the responsible of the error.
