### ISSUE TITLE
E-Mail issue after signature

### ISSUE THREAD

**Issue by ErminMerdanovic** [docusealco/docuseal#140]
Hello, I'm experiencing an issue when sending multiple different documents for signature to the same email address. Although the recipient receives all three emails and is able to sign each document, after completing the signatures, they only receive a copy of the first document they signed. Despite attempts to request copies of the other two documents through the website, either no copies are sent, or another copy of the first document is received instead of the remaining two documents.

**Comment by omohokcoj** [comment]
@ErminMerdanovic could you please provide some screenshots regarding how to reproduce it in the self-hosted app?

**Comment by ErminMerdanovic** [comment]
@omohokcoj i don't believe a screenshot will be helpful in this situation. Let me provide a more detailed explanation.

When I onboard a new customer, they typically need to sign three documents for me:

1. GDPR
2. Terms and Conditions
3. Wire Transfer Contract

For each of these documents, I have created a template in DocuSeal. I add the new customer's email address as a recipient for each document, and they receive the expected email notifications.

However, when the customer begins signing these documents one by one within a short timeframe, they should ideally receive a copy of the signed document along with an audit log for each. 

Unfortunately, for some reason, the copy of the document and the audit log are getting mixed up. Instead of receiving a copy for each document signed, the customer receives three copies of the first document, (the "GDPR" document) and does not receive any copies for the other signed documents.

**Comment by omohokcoj** [comment]
@ErminMerdanovic i was not able to reproduce this.
It seems like you have 3 templates and you send 3 separate signature request emails to your customers.
Then it seems like that they sign all 3 docs, and receive 3 emails with audit logs but those emails contain only the first template signed doc.
I can't see how this can be possible - maybe your customers resubmitted the first form three times and reported to you that the emails were wrong?

**Comment by omohokcoj** [comment]
> Despite attempts to request copies of the other two documents through the website, either no copies are sent, or another copy of the first document is received instead of the remaining two documents.

Maybe the other two PDF files can't be downloaded because of the PDF processing error (a small % of complex PDF can't be processed by the tool)
Docker logs might help to resolve the issue. Please feel free to reopen with the error logs.
@ErminMerdanovic
