### ISSUE TITLE
Does Docuseal "call home"?

### ISSUE THREAD

**Issue by infracritical** [docusealco/docuseal#143]
I work in a heavily regulated industry.  One of the requirements is external connectivity.  I need to know that the self-hosted version of Docuseal **does not** "call home".

Please advise.  Thank you.

**Comment by omohokcoj** [comment]
please reopen if you have any other questions

**Comment by graywolf336** [comment]
Is that github button still the only "phone home" that DocuSeal does? Or has a new one been added to keep track of usage?
