### ISSUE TITLE
Allow no SMTP authentication via GUI

### ISSUE THREAD

**Issue by alexismdr** [docusealco/docuseal#144]
As @ovizii explains [here](https://github.com/docusealco/docuseal/issues/23#issuecomment-1669033566), there's clearly some confusion that doesn't seem to be very clear : 

> I'm also confused why I can set these SMTP settings via variables AND via the GUI. If I set them via GUI I am forced to enter a user/password. Also, if I were to do that, would the GUI settings override the env variables?

A simple solution would be to allow the use of "none" authentication via the GUI (no authentication).

This is clearly necessary for a number of businesses that use SMTP servers that authenticate the client based on a list of IP addresses.

**Comment by omohokcoj** [comment]
@alexismdr it's currently allowed - username and password are optional fields now and so it's possible to authenticate SMTP without a password.

Please reopen if there is anything else we need to adjust
