### ISSUE TITLE
Unable to use TLS

### ISSUE THREAD

**Issue by alexismdr** [docusealco/docuseal#145]
See #93 for reference.

I'm sorry @AlexandrToorchyn but even if you check "TLS" this error is displayed. This forces me to use SSL, which doesn't help in my case. 🫤

_Originally posted by @alexismdr in https://github.com/docusealco/docuseal/issues/93#issuecomment-1812611199_

**Comment by omohokcoj** [comment]
@alexismdr that's a common error that happens because your SMTP server doesn't support TLS on the specified port.
Specifying a correct port should fix the error

**Comment by alexismdr** [comment]
I'm sorry @omohokcoj, but the SMTP server in question is Google's. I'd be surprised if it didn't support TLS!

**Comment by gbonazzoli** [comment]
@alexismdr @omohokcoj 

Same problem with libraesva SMTP/SSL on port 587. It is mandatory to set SMTP Security to None.
