### ISSUE TITLE
Server error on submission creation (API)

### ISSUE THREAD

**Issue by creizyz** [docusealco/docuseal#147]
When trying to create a new submission based on one of my templates, I am receiving a 500. I know what is wrong: by mistake, I have been sending the same submitter twice. But instead of returning a clear error, docuseal sends me this:

```json
{
    "status": 500,
    "error": "Internal Server Error"
}
```

The payload I am sending is:
```json
{
    "templateId": 11215,
    "submission": [
        {
            "submitters": [
                {
                    "application_key": "...",
                    "name": "...",
                    "role": "SELLER",
                    "email": "...@gmail.com"
                },
                {
                    "application_key": "...",
                    "name": "...",
                    "role": "SELLER",
                    "email": "...@gmail.com"
                }
            ]
        }
    ]
}
```

Just wanted this to be documented for your team.

**Comment by omohokcoj** [comment]
@creizyz 

 "templateId" - that's invalid param format
 we use "template_id" snake case format

**Comment by creizyz** [comment]
Oups, my bad ! Thx @)
