### ISSUE TITLE
Chinese characters support

### ISSUE THREAD

**Issue by zsinba** [docusealco/docuseal#148]
[2ddf8fc5-74c3-4d76-b24a-54b16384d1cc] HexaPDF::MissingGlyphError (No glyph for "张" in font 'Liberation Sans' found. 

Use the configuration option 'font.on_missing_glyph' to customize missing glyph handling.):

**Comment by AlexandrToorchyn** [comment]
@zsinba In our latest version 1.4.4, we have added support for multiple Asian languages, including Chinese. This update should help address the issue with the missing glyph

**Comment by zsinba** [comment]
Confirm that it is normal. Thank you
