### ISSUE TITLE
Integration with pad used to sign

### ISSUE THREAD

**Issue by tradexsrl** [docusealco/docuseal#149]
Hi , i'm evaluating your software installed with docker , created a template with a sign field.
everythings is ok except we should use pad to sign like signotec sigpad 100 (https://en.signotec.com/hardware/signature-pads/signotec-sigma/)
how can we sign directly in this screen with these kind of pad ?
![immagine](https://github.com/docusealco/docuseal/assets/62424179/89410fd7-e157-49e6-8434-d0ef92e49e68)
in the above screenshot the sign process is done directly with mouse but is very difficult to do and in our case we should use a pad; this pad could be activated by a web api call but how can we integrate this api request without modify your code base risking to loose it when the docker image is updated ?
other hardware solution accepted
thank's

**Comment by omohokcoj** [comment]
@tradexsrl integrating a hardware signature pad into a web app is complex and the integration differs per each manufacturer/model.
You're welcomed to create a PR for Sigpad 100 support and have it merged into upstream repo if you decide to go this path.
