### ISSUE TITLE
Create an open ended link

### ISSUE THREAD

**Issue by Lastofthefirst** [docusealco/docuseal#15]
I would like to be able to add a link to my website to a medical waiver, which could be signed by a visitor, and would with each signature be saved as a different document.

**Comment by NuttCorp** [comment]
Looking for the exact same thing. Need an open ended link that the user would have to first enter their email and then sign the document. Otherwise this is a beautiful app definitely donating.

**Comment by AlexandrToorchyn** [comment]
@Lastofthefirst @NuttCorp There is already a link that does exactly what you've described - it can be copied from the template page:

![share-link](https://github.com/docusealco/docuseal/assets/1176367/59c59af7-26d3-4520-bb91-8d4f78143849)

**Comment by NuttCorp** [comment]
Not in my setup. I also repulled the container and still no button. 
![Screenshot_2023-07-23-05-47-58-67_40deb401b9ffe8e1df2f1cc5ba480b12~2](https://github.com/docusealco/docuseal/assets/34084918/5e44e1b8-1a05-45b1-8dfb-3e5d787ccb96)

**Comment by AlexandrToorchyn** [comment]
@NuttCorp 
> Not in my setup. I also repulled the container and still no button.

That's because your template contains 2 submitters - this link works when the document contains only one submitter. With 2 submitters it's hard to determine which one of them has actually entered the form with this link - that's why the link was disabled in your example.

**Comment by NuttCorp** [comment]
I see the issue. That button is only there is there is a single submitter in the file.

**Comment by Lastofthefirst** [comment]
> @NuttCorp
> That's because your template contains 2 submitters - **this link works when the document contains only one submitter**. With 2 submitters it's hard to determine which one of them has actually entered the form with this link - that's why the link was disabled in your example.

That's the solution, I couldn't find it because I had multi submitter documents. Great tool,  thanks for developing and sharing!
