### ISSUE TITLE
[BUG] Removing BCC Adress causes Error 500

### ISSUE THREAD

**Issue by BlackJoker90** [docusealco/docuseal#151]
Hi,

as soon as I delete the E-Mail adress under notifications for bcc I get error 500.

![image](https://github.com/docusealco/docuseal/assets/75663091/e4c0b177-6ef8-4cfb-b504-f13f4cca30c7)

**Comment by omohokcoj** [comment]
@BlackJoker90 it has been fixed in the 1.3.0 release
