### ISSUE TITLE
[Feature Request] Disable typed signature

### ISSUE THREAD

**Issue by nichu42** [docusealco/docuseal#154]
I'd like to have the possibility to disable just typing the name in the signature field. It should allow hand-signed or uploaded signatures only. If possible, a global switch would be great, since I'd like to disable this for all future documents.

**Comment by omohokcoj** [comment]
@nichu42 thanks for the suggestion - it has been released in the new 1.3.1 version as well as in the Cloud:
![image](https://github.com/docusealco/docuseal/assets/5418788/6a1e8944-f540-49ee-889f-a7ee2649251d)

**Comment by tyrelb** [comment]
Thanks @omohokcoj for putting forth this change. I noticed that for embedded signatures, typed text signatures is still allowed even if allowed typed text signatures is disabled.  

<img width="571" alt="Screenshot 2023-12-27 at 9 49 16 PM" src="https://github.com/docusealco/docuseal/assets/217274/884f149f-f9e3-4876-a597-807ccfdd5231">
<img width="610" alt="Screenshot 2023-12-27 at 9 49 04 PM" src="https://github.com/docusealco/docuseal/assets/217274/51793599-6c69-4ca0-b9df-d9d2ad5a2e5b">

**Comment by omohokcoj** [comment]
@tyrelb sorry for the late reply and thanks for pointing this out!
This settings doesn't affect the embedded form - but recently we added an option to disable the 'typed signature' option in the embedded via the `data-allow-typed-signature="false"` attribute:
https://www.docuseal.co/docs/embedded

Let me know if this solves the issue
