### ISSUE TITLE
[Feature Request] Make status visible in overview

### ISSUE THREAD

**Issue by nichu42** [docusealco/docuseal#155]
I'm back with yet another wish :-)

Could you please make the status (sent / opened / completed) visible on the main page, maybe like this:

![grafik](https://github.com/docusealco/docuseal/assets/56028026/b739cb8f-ba3f-4b0e-ab01-1202cff9cd4f)

**Comment by omohokcoj** [comment]
@nichu42 one template can have multiple submissions with different statuses.
A better workflow for one-off signed docs will be provided via the 'Inbox' feature (eta January)
