### ISSUE TITLE
Unable to upload own/self-signed certs

### ISSUE THREAD

**Issue by hknobbe** [docusealco/docuseal#157]
Hi!

I have a small issue with uploading own / self signed certs.

Everytime I upload a cert (.P12 of .PFX), it gives the following error:

`Password is invalid. Make sure you're uploading a valid .p12 file `

This error always shows, with or without a password set on the cert.

**Information:**
- Self-hosted on Docker (:latest) (with postgresql).
- Multiple selfsigned certs tried.
- Logs don't show anything

Kinda at a loss as to what try next.

Hope you can help me or point me at the right direction.

Let me know if you need anything else!

Thanks!
Best Regards

Edit:
Tested the P12 files by adding them to Windows, Windows accepts them as a valid P12 file.

**Comment by hknobbe** [comment]
Sure!

Attachted the file, password: test

[blackCert.zip](https://github.com/docusealco/docuseal/files/13648103/blackCert.zip)

**Comment by AlexandrToorchyn** [comment]
@hknobbe I verified your certificate using this command:

```
openssl pkcs12 -info -in blackCert.p12
```

It looks like it is outdated or uses an unsupported algorithm. All I can do is suggest converting it to a modern format. Here are the instructions:

### 1. Creating a Temporary Legacy Certificate Copy:
Replace **CERTIFICATE_FILE_NAME** with the actual name of your PKCS12 certificate file.

~~~bash
cp CERTIFICATE_FILE_NAME.p12 temp_certificate.p12
~~~

### 2. Conversion to PEM Format:

Convert the **temp_certificate.p12** file from PKCS12 format to a **temp_certificate.pem** file in PEM format without encrypting the private key in the output file. Replace **CERTIFICATE_PASSWORD** with the actual password of the certificate.

~~~bash
openssl pkcs12 -legacy -in temp_certificate.p12 -out temp_certificate.pem -nodes -passin pass:CERTIFICATE_PASSWORD
~~~

### 3. Extracting the Private Key:

Extract the private key from the **temp_certificate.p12** file in PKCS12 format and store it in the **temp_certificate.key** file. The private key in the output file will be encrypted.

~~~bash
openssl pkcs12 -legacy -in temp_certificate.p12 -nocerts -out temp_certificate.key -passin pass:CERTIFICATE_PASSWORD -passout pass:'CERTIFICATE_PASSWORD'
~~~

### 4. Creating a New Certificate:

Generate a new **new_certificate.p12** file in PKCS12 format based on the private key from the **temp_certificate.key** file and the certificate from the **temp_certificate.pem** file.

~~~bash
openssl pkcs12 -export -out new_certificate.p12 -inkey temp_certificate.key -in temp_certificate.pem -passin pass:CERTIFICATE_PASSWORD -passout pass:CERTIFICATE_PASSWORD
~~~

### 5. Deleting Temporary Files:

~~~bash
rm -rf temp_certificate.p12 temp_certificate.pem temp_certificate.key
~~~

Done! Your certificate is now ready and named **new_certificate.p12**. You can utilize it for document signing.

**Comment by wrigjz** [comment]
We had the same issue, moving from openssl 1.1.x to 3.0.x for the final conversion to .p12 fixed it for us too.

**Comment by hknobbe** [comment]
Awesome, thanks! This helped.
