### ISSUE TITLE
Date format difference in viewed signed document to downloaded

### ISSUE THREAD

**Issue by wrigjz** [docusealco/docuseal#158]
We have noticed an interesting issue, if we use the Date field on a PDF it shows the date in the document as something like 11 December 2023 - which is great as it means there is not issue with DD/MM or MM/DD. However when we download the document the downloaded pdf says 11/12/2023.

This is using the simple Docker system on a ubuntu 22.04 system, the issue is the real showstopper for us as we need the PDFs to have the DD Month YYYY format to prevent issues.

![issue](https://github.com/docusealco/docuseal/assets/19869850/363539d2-50ff-4dd6-a615-8f6bf92e05ee)

**Comment by omohokcoj** [comment]
@wrigjz in the latest 1.3.3 version we added date field format configuration options and made the date format consistent across all document view pages in the app.
![image](https://github.com/docusealco/docuseal/assets/5418788/1c9584d8-04aa-415a-97b9-420ecd66fd80)
