### ISSUE TITLE
Status not present when getting a submission

### ISSUE THREAD

**Issue by eros404** [docusealco/docuseal#165]
I created a submission (from api) with 2 submitters.
I also signed the document with the first submitter.

When I do a GET request on `https://api.docuseal.eu/submissions/<SubmissionId>`, the field `status` is not present on the `submitters` objects.
But the field is present when I retrieve the submission in the list given with a GET request on `https://api.docuseal.eu/submissions`.

Tested with Postman.

**Comment by omohokcoj** [comment]
@eros404 status field and a list of signed documents has been added to the /submissions/<SubmissionId> API
https://www.docuseal.co/docs/api#get-a-submission
