### ISSUE TITLE
How to Integrate DocuSeal in Angular Project

### ISSUE THREAD

**Issue by g138** [docusealco/docuseal#166]
I am working on an Angular project and would like to integrate DocuSeal for document signing. I have reviewed the DocuSeal documentation, but I'm having difficulties figuring out how to properly integrate it into my Angular application.

I have raised a question on StackOverflow as well. https://stackoverflow.com/questions/77693545/how-to-integrate-docuseal-in-angular-project

@AlexandrToorchyn

**Comment by omohokcoj** [comment]
@g138   you just need to render <docuseal-form> HTML tag as in JS the example here:
https://www.docuseal.co/docs/embedded

Can you please share your code sample or error messages to figure out what is not working?

**Comment by omohokcoj** [comment]
Please reopen if you have any specific questions
