### ISSUE TITLE
Provide schema.json in docs

### ISSUE THREAD

**Issue by lukas-mertens** [docusealco/docuseal#167]
It would be great to have an openapi spec, e.g. as a schema.json linked on https://www.docuseal.co/docs/api to play around with the api easily using postman, insomnia or some other api client. This would make working with the api way easier

**Comment by omohokcoj** [comment]
@lukas-mertens Openapi specs are available here:
https://console.docuseal.co/openapi.yml

**Comment by lukas-mertens** [comment]
@omohokcoj Thanks a lot! For everyone else, it would still be great to put it in the docs ;)

**Comment by omohokcoj** [comment]
@lukas-mertens we provided a link to Openapi specs and Postman collection on the documentation page:
https://www.docuseal.co/docs/api
