### ISSUE TITLE
'{ production =>  }' is not a valid configuration. Expected '' to be a URL string or a Hash.

### ISSUE THREAD

**Issue by domhandy** [docusealco/docuseal#169]
I am trying to run docuseal (latest version) in kubernetes but I am getting an error message.
`ERROR -- : '{ production =>  }' is not a valid configuration. Expected '' to be a URL string or a Hash.`

I believe I have added all environment variables needed:

<img width="510" alt="image" src="https://github.com/docusealco/docuseal/assets/128103060/7eeabefa-a5b8-445c-822f-b557a709eedc">

**Comment by domhandy** [comment]
I got it working when I changed it to DATABASE_HOST, DATABASE_PORT, DATABASE_USER, DATABASE_NAME, and DATABASE_PASSWORD.

**Comment by omohokcoj** [comment]
Good to know that it worked for you, closing the issue 👍
