### ISSUE TITLE
Checkboxes not displaying correctly

### ISSUE THREAD

**Issue by f3st3r113** [docusealco/docuseal#17]
When creating checkboxes (male/female in this case), it displays as shown:

<img width="257" alt="Screenshot 2023-07-22 at 11 08 13 AM" src="https://github.com/docusealco/docuseal/assets/21040675/6244d4d7-367e-4440-a223-63bb0a1ee564">

**Comment by AlexandrToorchyn** [comment]
@f3st3r113 Already fixed in release 1.0.3. Thanks for reporting the bug 👍

**Comment by f3st3r113** [comment]
Confirmed! Thank you..
