### ISSUE TITLE
Question marks replace the X checked boxes from the Adobe Chrome Plugin form completion

### ISSUE THREAD

**Issue by sadohert** [docusealco/docuseal#172]
Environment:  Cloud
Account: Free

I'm attaching the document I just imported into the service to sign.  Its a "School Volunteer Application" form.  

* I received a pdf from the school that I opened in the Adobe Chrome Browser Tab view.
* I used the adobe view to complete most of the form.
* I noticed I needed a signature, so thought I would run the 99% completed form through Docuseal to add the signature
* When I imported, all the 'X" checks I had added using Adobe were converted to question marks (see attached).

BEFORE:
<img width="725" alt="image" src="https://github.com/docusealco/docuseal/assets/260544/0570fbdb-491d-4467-9dfc-ae1ae71ad57d">

AFTER:

<img width="1010" alt="image" src="https://github.com/docusealco/docuseal/assets/260544/0d6701ac-1ca9-43ec-ad88-14a34b752fcc">

Not a huge deal for me in this volunteer situation, but isn't ideal for business.

Here's the PDF (hopefully private details removed, someone please delete if not 🙏 )

[Appendix-A-Volunteer-Application.pdf](https://github.com/docusealco/docuseal/files/13815373/Appendix-A-Volunteer-Application.pdf)

**Comment by sadohert** [comment]
In the end when I downloaded the signed file the proper checkmarks were shown... so it was really only a visual issue in the UI for importing/editing the file.

**Comment by omohokcoj** [comment]
@sadohert thanks for reporting the issue - looks like the fonts packed into Docker image do not contain the checkmark glyph. We're working on adding support for more fonts/languages - hopefully it will be fixed with the updated fonts set packer into the docker image.

**Comment by omohokcoj** [comment]
@sadohert the issue with checkboxes has been fixed in the DocuSeal Cloud. Please let me know if everything works as expected now.

**Comment by sadohert** [comment]
I re-uploaded the same file and the check marks  looked good.  Thanks!
