### ISSUE TITLE
Allow changing of "Party" order

### ISSUE THREAD

**Issue by exo-pla-net** [docusealco/docuseal#174]
The "Party" order matters, since it controls the sequence of emails that are sent out.

Currently, there is no way to change the order, after you've created the parties.

In the template editor, you click a party and bring up the list of parties, you should be able to drag a party to change the order.

**Comment by omohokcoj** [comment]
@exo-pla-net buttons to reorder signing parties have been added in the latest 1.3.7 release
![image](https://github.com/docusealco/docuseal/assets/5418788/a0122e18-dfb1-4b30-8c6f-e9c6dac2f35a)
