### ISSUE TITLE
Fix inconsistent behavior of "Date" field versus "Signature" field

### ISSUE THREAD

**Issue by exo-pla-net** [docusealco/docuseal#175]
Currently, in the Template editor, clicking "Signature" both creates a new signature element and swaps to the signature tool, so you can draw the signature field.

However, when you click the "Date" button, it creates a new Date element but does *not* swap to the Date drawing tool.

When you click the Date button, it should swap to the Date drawing tool, for consistent behavior and better UI.

**Comment by omohokcoj** [comment]
@exo-pla-net in the 1.3.7 app version field drawing is enabled when clicking on all of the field type boxes on the right.
