### ISSUE TITLE
Make tooltip for placeholder inserts for invitation emails

### ISSUE THREAD

**Issue by exo-pla-net** [docusealco/docuseal#177]
In the invitation email form, there are placeholders such as:

{{template.name}}
{{submitter.link}}
{{account.name}}

All of these should be listed in a tooltip, so that they are accessible to the user, after they delete the default message and attempt to create their own custom message. (Otherwise, they will have no idea what placeholders are available.)

**Comment by omohokcoj** [comment]
@exo-pla-net hints with the available variable placeholders have been added in the latest release:
![image](https://github.com/docusealco/docuseal/assets/5418788/9e2b007c-6cb0-4d41-bb45-3708be864eb7)
