### ISSUE TITLE
the digital signature is invalid, you modify the original document after the first party sign. 

### ISSUE THREAD

**Issue by AbuHelweh** [docusealco/docuseal#179]
![image](https://github.com/docusealco/docuseal/assets/5153946/c899e45f-6621-4823-af6e-f2626ff46819)
 your project is excellent but the digital signature is invalid, when the second party sign in fact you modify the original document after the first party sign.

**Comment by omohokcoj** [comment]
@AbuHelweh  please check https://github.com/docusealco/docuseal/issues/163#issuecomment-1869466957
