### ISSUE TITLE
Split frontend into packages

### ISSUE THREAD

**Issue by vitormattos** [docusealco/docuseal#185]
Hi,

I'm the maintainer of [LibreSign](https://github.com/libresign/libresign) and I liked a lot the frontend of this project.

Would be possible start to move parts of frontend of this project to NPM packages to be possible use the frontend on other projects?

If yes, I can start helping to do this because I know that will be a big work and also will be necessary to create an organization at NPM.

I think that will be very nice to increase the contributions at frontend codebase.

**Comment by omohokcoj** [comment]
@vitormattos thanks for reaching out and for the feedback!
The app is mostly written in Rails with server side rendering - the only two JS UI components are the Form Builder and the Signing Form are written in Vue3.

I think extracting them into npm packages is not feasible in our case:
- This will slow down the development of our core DocuSeal app (it's a monolith and we want to keep it simple as it is now).
- The Form and the Builder UI use our DocuSeal API - it will be really hard to use it without DocuSeal with some other backend without proper docs. Also it will be really hard to implement those API for some new backend (literally requires to reimplement a large part of DocuSeal).
- We already offer users our convenient Embedded NPM packages to use our document signing UIs embedded into their apps but powered by DocuSeal API: https://www.npmjs.com/search?q=docuseal https://www.docuseal.co/docs/embedded
