### ISSUE TITLE
Removing a party from a template causes navigation to home page

### ISSUE THREAD

**Issue by jaredtbates** [docusealco/docuseal#191]
Hi, I'm using the DocuSeal builder JS with a pretty standard Angular SPA. However, I've noticed when I click the trash can to delete, or the re-order button, it causes the page to reload and navigate back to the home page.

<img width="344" alt="image" src="https://github.com/docusealco/docuseal/assets/2905521/430d6b3b-d5ef-48f6-8b28-bcd2a7591de7">

From what I can tell, it's because those buttons have `<a href="#">` on them but I'm not positive. Could you look into this? Thank you!

**Comment by omohokcoj** [comment]
@jaredtbates thanks for reporting this - it has been fixed in the Cloud Embedded JS. You might need to disable cache via dev console to get the new JS.

**Comment by jaredtbates** [comment]
@omohokcoj thanks so much! working great now
