### ISSUE TITLE
OpenAPI  spec should include schemas for return types of http calls

### ISSUE THREAD

**Issue by reckter** [docusealco/docuseal#195]
The spec document (https://console.docuseal.co/openapi.yml) currently only includes schemas for  the request parameters, but not for the returned types of the api. This means that, when generating a client with said schema, it will generate functions that return nothing (`void` in case of the `typescript-fetch` generator, I assume similar results, when using others).

I would have added schemas myself in an MR, but I don't think that yml is in any public repository?

**Comment by AlexandrToorchyn** [comment]
@reckter We've updated our spec document to now include comprehensive schemas that describe the types of attributes for all responses.

**Comment by omohokcoj** [comment]
closing this since response schemas have been already added to the openapi.yml
