### ISSUE TITLE
Stuck in a deadlock

### ISSUE THREAD

**Issue by lev-apeiros** [docusealco/docuseal#197]
Hi,
I have a weird situation:
I created a submission using the `/api/submissions` endpoint. I then archived the submission. When I call `/api/submissions` with the same submitters, it returns the same slug. However, when opening the link to sign the document, it says the document was deleted, and I have no way to unarchive the document or create a new submission.

There are two potential fixes that can help:
1. An ability to move the submission out of the archive.
2. To generate a new slug.

Currently, neither is supported. Any help will be appreciated.

**Comment by omohokcoj** [comment]
@lev-apeiros /api/submissions doesn't return the same slug - it always initiates a new submission and returns new submitters with new slug keys.
- maybe you're archiving templates/not submissions?
- maybe you copied template slug  instead of the individual slug keys?

**Comment by lev-apeiros** [comment]
Hi,
I found the problem. Because I was using Next.js `fetch`, it returned a cached response and the same slug was returned over and over again.
Fixed by adding:
```json
next: {
        revalidate: 0,
      }
```
Having said that, an ability to unarchive a submission would still be useful.
