### ISSUE TITLE
CORS error on Next.js

### ISSUE THREAD

**Issue by mnzsss** [docusealco/docuseal#198]
I used DigitalOcean for deploy aplication and when I try use the `DocusealForm` component of `@docuseal/react` package I got CORS error.

I use my host with SSL and consume the api with the another domain with SSL

Have a any solution or config for that?

```tsx
import { DocusealForm } from '@docuseal/react'

export default function DocuAssingn() {
 return (
    <DocusealForm
      src="https://self-hosted.com/d/slug"
      onComplete={(data) => console.log(data)}
    />
  )
}
```

![print](https://github.com/docusealco/docuseal/assets/51327920/6e0ac587-ac70-4aac-ada8-a8d79cf2be91)

**Comment by omohokcoj** [comment]
@mnzsss embedding is available only in DocuSeal Pro paid version (Cloud and Self-hosted).
The reason why you receive CORS and 404 is that embedding API is not available in open-source docuseal docker app.
We will improve the API to add a clear message about the features available in open-source.

**Comment by JapSeyz** [comment]
The same error seems to be present in prod, even on sandbox mode:

I am on sandbox, and supposedly have unlimited embeddings to test:

![image](https://github.com/docusealco/docuseal/assets/57725397/654847b2-c6c1-46ca-a89e-3857cb75e73e)


But when testing, I receive the same error as above:

If I pass an email attribute into the Vue component, it happens immediately, if I omit the email, it happens as soon as I click "Start"

![image](https://github.com/docusealco/docuseal/assets/57725397/46a80f7e-e1bd-42b9-97b5-e6144098bf7b)
![image](https://github.com/docusealco/docuseal/assets/57725397/ca1292e2-0af2-4957-8537-c2c90289a6ef)

Might be a bug, @omohokcoj ?

**Comment by omohokcoj** [comment]
@JapSeyz can you please share your embedding code/script?

**Comment by JapSeyz** [comment]
```pug
DocusealForm(
    :src="template"
    :role="role"
    logo="/images/logo.png"
    :skip-fields="false"
    :with-field-names="false"
    :with-title="false"
    :with-send-copy-button="false"
    :send-copy-email="false"
    @complete="onComplete"
  )
```

template = `https://docuseal.co/d/{SLUG}`
role = `Test A/S`

**Comment by omohokcoj** [comment]
@JapSeyz role 'Test A/S' doesn't exist in your template (only one role names 'First Party' is present in the template)

**Comment by JapSeyz** [comment]
Oh, those two has to match? I was not aware. It's quite an obscure error to throw for that, but thank you for the swift response

**Comment by omohokcoj** [comment]
@JapSeyz yeah we need to improve the error handling in embedding - the error message is correct in the API response - the problem is that it doesn't include CORS headers and was blocked by the browser. We will add CORS headers and make the error messages visible in the next release. Thanks for pointing this out

**Comment by JapSeyz** [comment]
Alright, thank you. And again, thanks for the extremely swift response
