### ISSUE TITLE
`fields` key of second submitter seems to be ignored

### ISSUE THREAD

**Issue by ko-pp** [docusealco/docuseal#200]
Hello

I am currently testing DocuSeal with a two-parties template and sending through the API.

We have a bunch of values for each party but they are all filled by us and set as readonly in the API payload, except for one field per party (plus signature) that has a validation pattern and an error message.

With the first party, everything work as expected*, but for the second one, every field stays RW and the validation pattern is ignored (the attribute is missing on the input element), which seems to point to `fields` being ignored for the second submitter.

* well, almost https://github.com/docusealco/docuseal/issues/199

**Comment by omohokcoj** [comment]
@ko-pp thanks for reporting this - there was a bug that prevented the correct assignment of default values of the 2nd+ parties.
It's has been already fixed on production Cloud and will be released in the open-source app next week.

**Comment by ko-pp** [comment]
It does work for us on the Cloud’s testing env.
Thank you
