### ISSUE TITLE
`application_key` is null on webhook request

### ISSUE THREAD

**Issue by jaredtbates** [docusealco/docuseal#201]
Hello,

I have a form set up like below. It sent the string for `application_key` in the webhook request one time but now does not. I do see this in the http requests: 
<img width="456" alt="image" src="https://github.com/docusealco/docuseal/assets/2905521/fbde580a-b648-4a11-aff1-4f0efe8de53c">

We aren't sure why this is happening. We're almost to the end of our integration. Could someone take a look?

```html
      <script type="text/javascript" src="https://cdn.docuseal.co/js/form.js"></script>
      <docuseal-form
        data-src="https://docuseal.co/d/abcdefghijk"
        data-application-key="17fab1c5-c551-4bc8-b372-cfa5e4737931"
        data-with-title="false"
        data-allow-to-resubmit="false">
      </docuseal-form>
```

**Comment by omohokcoj** [comment]
@jaredtbates do you load applicationKey from async your backend API to insert in into the attribute with angular?
In this case you might need to add if condition to render <docuseal-form only once the applicatioKey is loaded.
Mounting <docuseal-form in the DOM triggers a request to initiate a submission so the submission might be initiated without the applicationKey if it was loaded later.

In the resent updates we made <docuseal-form attributes reactive and trigger API request to reinitiate the submission - but it's always better to load everything and only then render/mount <docuseal-form on the DOM.

Let me know if it helped to resolve the issue.

**Comment by jaredtbates** [comment]
Hi @omohokcoj, I tried clearing my cache and also tried making an `index.html` form with just the provided HTML above and had the same issue. I see the /forms endpoint call is sending the application_key I specified but later it is `null`.

<img width="1158" alt="image" src="https://github.com/docusealco/docuseal/assets/2905521/8edb67b0-1826-4693-8984-fd1169c0b847">

<img width="775" alt="image" src="https://github.com/docusealco/docuseal/assets/2905521/ba91e7be-126b-4aec-9ec4-6cdd3ecb5dcb">

**Comment by omohokcoj** [comment]
@jaredtbates thanks for sharing those screenshot - i think it helped us to identify the issue.
Can you please refresh the page (disable cache in dev console jut in case) and try to sign again with application key?
Let me know if it works now with the recent update.

**Comment by jaredtbates** [comment]
Thank you! It's working great now!
