### ISSUE TITLE
Misspelling of created_by_user  as creared_by_user in documentation

### ISSUE THREAD

**Issue by justindmyers** [docusealco/docuseal#202]
I noticed a misspelling in the documentation of [List all submissions](https://www.docuseal.co/docs/api#list-all-submissions) and [Get a submission](https://www.docuseal.co/docs/api#get-a-submission) where the property is spelled `creared_by_user` instead of `created_by_user`

![Screenshot 2024-01-25 123440](https://github.com/docusealco/docuseal/assets/58646/1760a17e-484c-41ea-8022-15e277ea65f5)

**Comment by omohokcoj** [comment]
@justindmyers thanks! we've updated the docs:
![image](https://github.com/docusealco/docuseal/assets/5418788/99c1ab6d-8e5a-48e7-853a-585fba837c6f)
