### ISSUE TITLE
General questions of what DocuSeal can do

### ISSUE THREAD

**Issue by Tizzzzy** [docusealco/docuseal#203]
Hi, huge fan of your work. I have some general questions about this project.

1. Does the system support online drafting of contracts, i.e., without the need for uploading, and provide specific contract templates?
2. Does the system support uploading .docx or .doc files for online modification of contract content?
3. Does the system support marking specific fields in the contract as 'required', and for required fields, must content be filled in to complete the contract drafting?
4. Does the system display modification records, support version comparison, and version recovery?
5. Does the system support downloading either the review or non-review version of a document?
6. Does the system support sending .docx files to an assistant API for analysis?
7. Does the system support selecting specific sentences within a document to trigger AI interpretation?
8. Does the system offer side-by-side AI analysis, and for the specific content given by the analysis, locate the related position in the document?

**Comment by omohokcoj** [comment]
hi @Tizzzzy 
1. no, that's not a goal
2. only in the cloud or Pro on-prem
3. yes
4. PDF can do that, all changes in the PDF are maid as a new 'layer' which can be reviewed via Adobe Acrobat
5. no
6. no
7. no
8. no
