### ISSUE TITLE
Support for offline electronic id signature

### ISSUE THREAD

**Issue by bendem** [docusealco/docuseal#205]
I haven't seen if this is supported or not but based on the discussion [here](https://github.com/docusealco/docuseal/discussions/89), I'm guessing not.

Is there support for smartcard based signing as used in European countries ? I'm speaking about https://ec.europa.eu/digital-building-blocks/DSS/webapp-demo/home, https://sign.fts.bosa.belgium.be/, etc.

The signature is fully offline and you can retrieve the CAs for each country from the [european trusted list](https://ec.europa.eu/digital-building-blocks/DSS/webapp-demo/tl-info).

**Comment by omohokcoj** [comment]
@bendem currently it's not implemented but that's something we have in the roadmap (can't provide the exact ETA - hopefully later this years - depends on the real demand for this feature)

**Comment by bendem** [comment]
You closed the issue so I have no way to know if something happened, and people can't vote for it. Is this still on the roadmap?
