### ISSUE TITLE
Automatically replicate information in fields with the same Data Label

### ISSUE THREAD

**Issue by imbkr** [docusealco/docuseal#209]
Do we have this feature? we use this feature to replicate the data across multiple pages.

**Comment by omohokcoj** [comment]
@imbkr you can draw the same field multiple times on a different place/page - this way the signers need to fill it once and it will be added to the PDF multiple times:
![image](https://github.com/docusealco/docuseal/assets/5418788/0d2fc259-d553-427a-ad1c-28bc882726e8)
