### ISSUE TITLE
Error 500 when downloading files

### ISSUE THREAD

**Issue by chennien** [docusealco/docuseal#211]
The cloud version of Docuseal malfunctioned at 05:00 on February 13, 2024 (UTC). Error 500 occurred when trying to download any PDF file. It was working yesterday.

![Docuseal_download_malfunctioned_20240213](https://github.com/docusealco/docuseal/assets/75157/3febff31-9b6a-4447-aec7-77ca304cb2b6)

**Comment by omohokcoj** [comment]
@chennien we do not support chinese characters in the PDF yet - it results in 500
