### ISSUE TITLE
No Audit Report for Documents with Foreign Characters When Being Signed 

### ISSUE THREAD

**Issue by jimewu** [docusealco/docuseal#213]
I am running docuseal service as a docker container. I have a document with foreign characters (CJK) when being signed, and no audit report button was shown. I checked the log (`docker logs`) and found the following message:

```
E, [2024-02-14T11:46:38.440767 #1] ERROR -- : [ActiveJob] [ProcessSubmitterCompletionJob] [934e7b5e-1b65-464b-b08f-9e2d863faf0b] Error performing ProcessSubmitterCompletionJob (Job ID: 934e7b5e-1b65-464b-b08f-9e2d863faf0b) from Async(default) in 797.55ms: HexaPDF::MissingGlyphError (No glyph for "測" in font 'Liberation Sans' found. 
```

I found a solution for new documents with CJK characters, in which I added the following in docker-compose.yml:

```
volumes:
      - /fonts/NotoSansCJKtc-Regular.ttf:/fonts/LiberationSans-Regular.ttf
      - /fonts/NotoSansCJKtc-Bold.ttf:/fonts/LiberationSans-Bold.ttf
```

With the above settings that overwrite LiberationSans-Regular.ttf and  LiberationSans-Bold.ttf with CJK-supported fonts, newly signed documents with CJK characters showed the audit report button. However, those already-signed documents still have no audit report button shown. Any suggestions please?

**Comment by AlexandrToorchyn** [comment]
@jimewu Thanks for sharing the details. In our latest release, 1.4.4, we have added support for several Asian languages, including Chinese. This should fix the issue with the missing audit report button for documents with CJK characters.

If documents signed before the update still don't show the audit report button, try re-signing them with the updated DocuSeal version.
