### ISSUE TITLE
Errors in Webhooks doc

### ISSUE THREAD

**Issue by ko-pp** [docusealco/docuseal#221]
Hello

The [Webhooks documentation](https://www.docuseal.co/docs/api#form-webhook) has a few issues:
- the  example misspelled `data.application_key` as `data.aplicattion_key` 
- the example is missing `data.submission_url`
- both the description and example have a `data.submission.updated_at` that is missing from the actual payload (at least in the cloud testing env)

**Comment by AlexandrToorchyn** [comment]
@ko-pp Good catch! Thanks for letting us know
