### ISSUE TITLE
Unable to Use SMTP Server with TLS v1.2/v1.3

### ISSUE THREAD

**Issue by samgerstner** [docusealco/docuseal#226]
Using DocuSeal v1.4.5 Community Edition via Docker Compose

**Issue Description**: When attempting to modify the Email SMTP settings from Settings > Email I get the following error when attempting to save my settings: `SSL_connect returned=1 errno=0 peeraddr=X.X.X.X:587 state=error: wrong version number`

I am running my own SMTP server with Postfix (version 3.6.4) and Dovecot (version 2.3.16) that requires TLS encryption via port 587. The server has also disallowed TLS protocol v1.1 as it is no longer considered secure. As mentioned, when I attempt to save my SMTP settings when pointed to the described server, I get the referenced error. There don't appear to be any relevant log entries in the docker container's logs.

Docker Logs: https://pastebin.com/jP3rYqEy

![smtp_error](https://github.com/docusealco/docuseal/assets/66745349/3f47f42f-074b-4a8d-a332-02f6621d63ac)

**Comment by omohokcoj** [comment]
Hi @samgerstner probably your mail server supports STARTTLS - Auto STARTTLS is enabled by default so SMTP should work with 'None' (instead of force TLS).
