### ISSUE TITLE
podman (rootless) container failing on 1.4.5 / 1.4.6

### ISSUE THREAD

**Issue by pie-rs** [docusealco/docuseal#227]
Hi,

The latest two releases seem to fail on docker.  1.4.4 is running fine.

I am running alma9 5.14.0-284.25.1.el9_2.aarch64

podman 4.6.1 rootless

podman run \
	-it \
	--sdnotify=conmon \
	--replace \
	--label io.containers.autoupdate=image \
	--name docuseal \
        -p 3000:3000 \
        -e WEBHOOK_URL=https://SECURE.MYDOMAIN.COM/ \
        -e DATABASE_URL=postgresql://docuseal_prod_user:MYPASSWORD@10.0.0.147:5432/docuseal_prod \
        -e FORCE_SSL=${HOST} \
        -v /etc/localtime:/etc/localtime:ro \
        -v /home/webapps/docuseal/data:/data:Z \
        docker.io/docuseal/docuseal:1.4.6

(using real domain and password)

The container is sitting behind caddy.  All other containers are still running fine.   Version 1.4.4 runs fine.

stdout:

WARNING: Nokogiri was built against libxml version 2.11.6, but has dynamically loaded 2.11.7
=> Booting Puma
=> Rails 7.1.2 application starting in production
=> Run `bin/rails server --help` for more startup options
Exiting
/usr/local/bundle/gems/rack-2.2.8/lib/rack/server.rb:446:in `delete': Resource busy @ apply2files - /dev/null (Errno::EBUSY)
	from /usr/local/bundle/gems/rack-2.2.8/lib/rack/server.rb:446:in `check_pid!'
	from /usr/local/bundle/gems/rack-2.2.8/lib/rack/server.rb:307:in `start'
	from /usr/local/bundle/gems/railties-7.1.2/lib/rails/commands/server/server_command.rb:38:in `start'
	from /usr/local/bundle/gems/railties-7.1.2/lib/rails/commands/server/server_command.rb:145:in `block in perform'
	from <internal:kernel>:90:in `tap'
	from /usr/local/bundle/gems/railties-7.1.2/lib/rails/commands/server/server_command.rb:136:in `perform'
	from /usr/local/bundle/gems/thor-1.3.0/lib/thor/command.rb:28:in `run'
	from /usr/local/bundle/gems/thor-1.3.0/lib/thor/invocation.rb:127:in `invoke_command'
	from /usr/local/bundle/gems/railties-7.1.2/lib/rails/command/base.rb:178:in `invoke_command'
	from /usr/local/bundle/gems/thor-1.3.0/lib/thor.rb:527:in `dispatch'
	from /usr/local/bundle/gems/railties-7.1.2/lib/rails/command/base.rb:73:in `perform'
	from /usr/local/bundle/gems/railties-7.1.2/lib/rails/command.rb:71:in `block in invoke'
	from /usr/local/bundle/gems/railties-7.1.2/lib/rails/command.rb:149:in `with_argv'
	from /usr/local/bundle/gems/railties-7.1.2/lib/rails/command.rb:69:in `invoke'
	from /usr/local/bundle/gems/railties-7.1.2/lib/rails/commands.rb:18:in `<main>'
	from <internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
	from <internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
	from /usr/local/bundle/gems/bootsnap-1.17.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
	from /app/bin/rails:4:in `<main>'

Any help would be appreciated - let me know if I can provide more information.

**Comment by omohokcoj** [comment]
@pie-rs eddint PID env variable should fix the issue on LXC:
https://github.com/docusealco/docuseal/issues/224#issuecomment-1974801465

**Comment by pie-rs** [comment]
amazing that solved it thank you @omohokcoj
