### ISSUE TITLE
UETA and ESIGN Act

### ISSUE THREAD

**Issue by grintor** [docusealco/docuseal#228]
Hello,

Does DocuSeal meet the legal requirements for digital signing under the [UETA and ESIGN Act](https://www.docusign.com/learn/esign-act-ueta)?

What about 21 CFR Part II? (same link, but further down the page)

**Comment by omohokcoj** [comment]
@grintor you can find more here: https://www.docuseal.co/compliance
Also here is an existing discussion: https://github.com/docusealco/docuseal/discussions/20

**Comment by grintor** [comment]
I've reviewed your SaaS offering for compliance and I've noted two issues you have that run the product astray of the regulations.

1) When using the "Set Signing Date" option, what the signer sees in the date field when signing is "{{date}}" (even after they have signed), but in the downloaded PDF, that field is populated with today's date. It's not permitted for the document contain different information than what was presented to the user.

2) When using the "stamp" feature, Docuseal will certify that a user has electronically signed the document even if they did not sign it, but only filled out a text field.
