### ISSUE TITLE
Variable "submitter.link" contains a tracker

### ISSUE THREAD

**Issue by juergenbarth** [docusealco/docuseal#231]
Hi,

I found this interesting behaviour while testing:

Once the variable

`{{submitter.link}}`

is expanded in the e-mail, it contains a tracker in the form of

https://https://4twxcshy.r.eu-west-1.awstrack.me/L0/https:%2F%2Fexample.com%2Fs%2FyZtvDiJYejGz4y%3Ft=eVp0dk/1/0102018e332bd17c-355710ef-fa6b-4916-8a3d-1a8ee157a20e-000000/PErJE3YyCDoKFnKcYTlr4bfq9vo=365

Could you please explain which data is collected, where it is used and for which purpose?
How can the be turned off?

Thanks!

**Comment by omohokcoj** [comment]
@juergenbarth docuseal does not track self-hosted app links - the link you shared is from AWS SES (the email service you're using when selfhosting). YOu can disable it on AWS SES: 
https://stackoverflow.com/questions/59044099/stop-ses-from-adding-awstrack-me-to-all-my-email-links
