### ISSUE TITLE
Sophisticated/Pro Version: Allow link sharing for forms with multiple parties

### ISSUE THREAD

**Issue by lukas-mertens** [docusealco/docuseal#237]
---

**Extension/better version of my proposed solution in: #236**

---

## Background and Problem
As previously discussed in the docuseal discord channel, the current DocuSeal system does not adequately support scenarios where multiple, unknown parties need to sign a document without prior invitation. Attempting to access the form via a shared link results in a "not found" error, causing confusion for users.

## Proposed Enhancement for Pro Version
To enhance user experience and accommodate multi-party signing scenarios, I propose the following feature for the Pro version of DocuSeal (or open source, but I do understand you have to earn money somehow):

**Workflow Overview:**
1. A primary party, such as a parent, initiates the document signing process by completing their portion of the form and indicating consent.
2. Upon completion, the system presents a dynamically generated invitation interface allowing the primary party to enter one or more email addresses for subsequent signers.
3. The next party, such as an authorized adult, receives an email request to sign the form and has the option to input additional email addresses if necessary.

**User Interface:**
- The form interface will clearly display the signing status of each party:
  - Parent (You): Signed ✅
  - Authorized Adult: [Pending/Email input field]
  - Additional Party: [Pending/Email input field]
  - ... (and so on for additional parties as required)

## Rationale
This feature is particularly needed for organizations like NGOs that organize events requiring parental consent for child supervision by varying responsible adults. The ability to share a form link broadly, while still capturing required consents and responsibilities, is crucial.

## Expected Impact
- Streamlines the process for events with variable adult supervision requirements.
- Reduces administrative burden and error potential by removing the need for pre-defined party lists.
- Enhances the flexibility of the form signing process to accommodate last-minute changes in responsible adults.

**Comment by omohokcoj** [comment]
Hi @lukas-mertens in the new version it's possible to mark a signing party by invited by another signer
https://www.docuseal.co/resources/invite-a-witness-by-the-signer - the invitation via email happens right before the signature completion.
Closing the issue - please reopen if this feature doesn't solve the mentioned problem.
