### ISSUE TITLE
Database issue (?) in Docker

### ISSUE THREAD

**Issue by tgranqvist** [docusealco/docuseal#238]
Hello

I am trying to run an instance od DocuSeal on my Synlogy, using the fairly new Container Manager as Docker interface. 
I am using this compose file, based off of your example one from [https://www.docuseal.co/install](https://raw.githubusercontent.com/docusealco/docuseal/master/docker-compose.yml)

```Compose
services:
    app:
        image: docuseal/docuseal:1.4.7
        depends_on:
            postgres:
                condition: service_healthy
        ports:
            - 3000:3000
        volumes:
            - .:/data
        environment:
            - FORCE_SSL=true
            - DATABASE_URL=postgresql://postgres@postgres:5432/docuseal
            - PIDFILE=/tmp/server.pid

    adminer:
        image: adminer:4.8.1-standalone
        ports:
            - 8090:8080

    postgres:
        image: postgres:16.2-alpine3.19
        volumes:
            - ./db:/var/lib/postgresql/data
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=docuseal
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres"]
            interval: 5s
            timeout: 5s
            retries: 5
```

The instance builds all right, the database and Adminer instance stays running. But the app container itself only runs for about a minute, then shuts down. I get this error in the container log. Seems like it can't talk to the database. 
![image](https://github.com/docusealco/docuseal/assets/24589919/25a12587-4b2b-4d06-bf4c-33e87437a79d)

However, the Adminer started in the same compose file has no issue connecting or sending queries to the server.
![image](https://github.com/docusealco/docuseal/assets/24589919/900c2ee3-25ad-4572-88ab-829a65323762)

I expose my services through Cloudflare tunnel, running in another container, and can reach both Adminer and other services through that.

**Comment by omohokcoj** [comment]
@tgranqvist you need to specify a password in the DB URL
![image](https://github.com/docusealco/docuseal/assets/5418788/68603209-f09d-44c3-893d-6bbca8cc49a1)

**Comment by tgranqvist** [comment]
Yeah, I figured it a minute after I subittmed the ticket. I **swear** I went through the config a dozen times, haha.
