### ISSUE TITLE
Error with docker install

### ISSUE THREAD

**Issue by HumanG33k** [docusealco/docuseal#239]
On current debian testing, not a docker expert. 

```
sudo docker run --name docuseal -p 3000:3000 -v.:/data docuseal/docuseal
[...]
Unable to find image 'docuseal/docuseal:latest' locally
latest: Pulling from docuseal/docuseal
[...]
Status: Downloaded newer image for docuseal/docuseal:latest
docker: Error response from daemon: create .: volume name is too short, names should be at least two alphanumeric characters.
```

**Comment by omohokcoj** [comment]
@HumanG33k which version of docker are you using?

**Comment by omohokcoj** [comment]
@HumanG33k it seems like the issue is caused by the old docker version

**Comment by HumanG33k** [comment]
hi @omohokcoj  
Sry for "late" response but for me github issue is like irc (slow communication way). 

I know debian stuff is "old", i will retry soon, but for what i remember i used debian testing. 

Is there is a manual install documentation somewhere ? find nothing about in https://www.docuseal.co/docs or in the readme. Maybe i should just read the docker compose ?

**Comment by vovcacik** [comment]
Resolved by
```
docker image pull docuseal/docuseal
dockercli -SwitchLinuxEngine
sudo docker run --name docuseal -p 3000:3000 -v.:/data docuseal/docuseal
```
