### ISSUE TITLE
FORCE_SSL=false still forces ssl

### ISSUE THREAD

**Issue by Trauer** [docusealco/docuseal#241]
Like the title said, using docker with FORCE_SSL=false but it still forces https and gets "HTTP parse error, malformed request: #<Puma::HttpParserError: Invalid HTTP format, parsing fails. Are you trying to open an SSL connection to a non-SSL Puma?>"
error

**Comment by omohokcoj** [comment]
@Trauer thanks for reporting this - it has been fixed in 1.4.9

**Comment by schtack** [comment]
i'm getting the same error after the update

**Comment by omohokcoj** [comment]
@schtack FORCE_SSL=false disabled https redirect on 1.4.9 version.
Make sure you're using http (https redirect might be cached in browser)
