### ISSUE TITLE
content from forms missing on pdf export

### ISSUE THREAD

**Issue by avatar1024** [docusealco/docuseal#244]
Hello,

Since recently (sorry I can't tell precisely when the changed occurred but the issue wasn't there in Feb 24), I have an issue with signed document that were made from pdf with embedded forms.

Any content added to the document

Within the Docuseal interface, the document template and the final signed document both have the content of the form filled in (as per the original pdf it's based on). However when I export the pdf (or the pdf that got sent around after signing), the content of the forms are blank. This didn't use to be the case a few month ago.

For clarity, any fields filled via Docuseal (text, dates, signatures, etc) are present as normal in the final PDF, only the content of the forms in the original PDF are now missing.

Also I haven't reloaded a new PDF or anything, I'm using the same template inside Docuseal I used a few month ago.

**Comment by avatar1024** [comment]
[RR_model_tenancy_1.2_shared_house_annonymous.pdf](https://github.com/docusealco/docuseal/files/14804158/RR_model_tenancy_1.2_shared_house_annonymous.pdf)

Thank you for the reply and for looking into this. Here it is attached (well I've slightly modified it to anonymise it, hopefully that won;t change the outcome)

Using Docuseal 1.4.9 btw

**Comment by omohokcoj** [comment]
@avatar1024 i just tried it myself and it work - existing fields data is present on the page in the signed PDF
![image](https://github.com/docusealco/docuseal/assets/5418788/f211feb8-e838-4beb-91d1-e0cb9bc02caa)
[RR_model_tenancy_1.2_shared_house_annonymous (1).pdf](https://github.com/docusealco/docuseal/files/14804181/RR_model_tenancy_1.2_shared_house_annonymous.1.pdf)

**Comment by avatar1024** [comment]
Wait, actually I've just tried to save a copy with PDF arranger, which also doesn't support. The original document I used returns blank, the modified copy I sent you returns filled in.

Here is the original one...

[RR_model_tenancy_1.2_shared_house.pdf](https://github.com/docusealco/docuseal/files/14804201/RR_model_tenancy_1.2_shared_house.pdf)

**Comment by omohokcoj** [comment]
@avatar1024 thanks for sharing this PDF - indeed there is an issue with, we will investigate it farther
![image](https://github.com/docusealco/docuseal/assets/5418788/dddf7e61-5cb6-4174-8632-1cf2ed737fa1)

**Comment by avatar1024** [comment]
To make the anonymised version I modified the fields using my PDF reader (Okular), and it seems like all fields modified with it now show up fine (I just tried one modifying only some of the fields, and only the modified fields show up, while the others remain blank). 

I'll tried re-exporting the original .odt doc to PDF with LibreOffice and see what happens and get back to you (as those documents are old maybe the PDF export done back in the day now don't comply with more modern way to handle forms which make it fails with both Docuseal and PDF Arranger - even if odd as they use to work fine just a a bit ago).

**Comment by avatar1024** [comment]
Just tried to re-export the doc the PDF via Libreoffice. The forms show up with the right content in the created PDF, but when resaved with PDF Arranger the form are blank again. Although in the blank document, if I click "Show form" with PDF reader (Okular) in order to edit then all the content show up, but disappear again when I stop. Only if I modify a field then the content (only of the modified field) remains.

Hopefully those additional info might help the debugging.

**Comment by navdeepghai1** [comment]
@avatar1024 I guess its a common issue, It's happening with our pdfs also.
Docuseal somehow while flattening PDF forms removing all the fields from the signed document even tho PDF is set to readonly.

I guess flattening PDF Form shouldn't be applied on readonly fillable pdfs.

**Comment by omohokcoj** [comment]
@navdeepghai1 can you please share your PDF to investigate the issue  ?

**Comment by navdeepghai1** [comment]
Original PDF:
[original-pdf.pdf](https://github.com/docusealco/docuseal/files/15065874/original-pdf.pdf)

Screenshot before signing the PDF:
![Screenshot 2024-04-22 at 12 22 50 PM](https://github.com/docusealco/docuseal/assets/30634335/746efa40-4f19-4d37-98af-06d71c040316)


PDF I received from Docuseal after signing the document:
[BOR-93d15e8b1e.pdf](https://github.com/docusealco/docuseal/files/15065839/BOR-93d15e8b1e.pdf)


NOTE:
We're using pypdf's PDFWriter class to prefill the values from the backend then marking it as readonly and sending it to the docuseal to generate the signature.

**Comment by omohokcoj** [comment]
@navdeepghai1 the original [original-pdf.pdf](https://github.com/docusealco/docuseal/files/15065874/original-pdf.pdf) you shared doesn't contain values in the PDF form fields - can you please share a PDF which filled PDF fields which are removed after the document is signed via docuseal?

**Comment by omohokcoj** [comment]
@navdeepghai1 @avatar1024 in the new version we added a toggle to the /settings/esign to disable PDF from removed from the completed documents - so turning it off should preserve the fields with values in the PDF

**Comment by omohokcoj** [comment]
@navdeepghai1 @avatar1024 the bug has been fixed in the latest 1.5.8 version
