### ISSUE TITLE
BASE URL SET 

### ISSUE THREAD

**Issue by nkumarankr** [docusealco/docuseal#247]
I ran a project on the server using docker, I set a domain name like https://nkumar.800ambi.com/docuseal, how can set baseurl in this project, when I install the project in the local machine working fine but if I change any text  in templets  no effect in the project, after change content, I did  docker-compose up, still not reflecting that text

**Comment by omohokcoj** [comment]
@nkumarankr app base URL can't include a folder - it should be a root url https://docuseal.nkumar.800ambi.com for instance
