### ISSUE TITLE
**Recommendation** with Digital Ocean 1-click Install

### ISSUE THREAD

**Issue by philozofer** [docusealco/docuseal#248]
The issue arises when we install and deploy DocuSeal with the 1-click installation process.
After the build is completed, the deployment always fails due to this line as seen from the logs :  

 raise ArgumentError, "`secret_key_base` for #{Rails.env} environment must be a type of String`"

````
 Puma starting in single mode...
 * Puma version: 6.4.0 (ruby 3.2.2-p53) ("The Eagle of Durango")
 *  Min threads: 15
 *  Max threads: 15
 *  Environment: production
 *          PID: 1
 WARNING: Nokogiri was built against libxml version 2.11.6, but has dynamically loaded 2.11.7
 ! Unable to load application: ArgumentError: `secret_key_base` for production environment must be a type of String`
 bundler: failed to load command: puma (/usr/local/bundle/bin/puma)
 /usr/local/bundle/gems/railties-7.1.2/lib/rails/application.rb:653:in `validate_secret_key_base': `secret_key_base` for production environment must be a type of String` (ArgumentError)

raise ArgumentError, "`secret_key_base` for #{Rails.env} environment must be a type of String`"
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
````

I would suggest to be explicit to the user and mention somewhere on the **docuseal.co/install** page to create an account first to have the API Key generated and prepared to be used. 

![image](https://github.com/docusealco/docuseal/assets/9042494/390f3dd1-fcf3-4f8a-859d-f59d7f9c9014)

Since after clicking on the *Deploy to Digital Ocean* installation, it launches right away and proceeds to the build phase. It then tries to deploy, but it **WILL** fail, since the user had no indication/time to fill in the *SECRET_KEY_BASE* in the settings of the application.

![image](https://github.com/docusealco/docuseal/assets/9042494/ece0519e-fae2-4f96-aec8-3049927133f9)

Some other competitors have the 1-click install and all is well. I do not think it an API error should occur in the installation process. 
Could the API Key be supplied at a later time ?

**Comment by omohokcoj** [comment]
Hi @philozofer DO installation should work when following those instructions: https://github.com/docusealco/docuseal-digitalocean
Let me know if it solves the issue

**Comment by philozofer** [comment]
Thank you for the swift reply! @omohokcoj 

With the directives of the github docs, yes it works perfectly.
These were the steps I manually did when the deployment failed.
There should be a transition screen with the corresponding docs of each 1-click installation.

From here (**docuseal.co/install**), each action button could lead to their specific DOC-INSTALL screen:
![image](https://github.com/docusealco/docuseal/assets/9042494/09661d7f-6f17-46bc-95f5-67c8e3e3da55)

which contains the information you linked :
https://github.com/docusealco/docuseal-digitalocean

![image](https://github.com/docusealco/docuseal/assets/9042494/dbb5f9bb-9830-479c-84d9-8b1d8a45d0fe)

And have the button on that page be the action button to launch the Digital Ocean installation process ?

Thanks for your app, will be testing it and most likely adopt it for our enterprise needs.
