### ISSUE TITLE
Landscape Signing Issues

### ISSUE THREAD

**Issue by estallio** [docusealco/docuseal#249]
Hi!

I was observing that people are turning their phone in landscape mode for signing PDFs with DocuSeal. However, when the phone is in landscape mode, the scrolling area at the top is so small and the signing-area is fixed and can not be dismissed. See the screenshot of my iPhone 11 Pro:
![90079069-413B-4398-BF6B-9D9DD3D6B29D_1_201_a](https://github.com/docusealco/docuseal/assets/26573555/824afd0a-9a4f-4fc9-9a36-b02f15d4de91)

Similarly, it is confusing when I turn my phone from portrait mode:
![B6646BCA-21AD-4E12-87FB-201D2AD865D8_1_201_a](https://github.com/docusealco/docuseal/assets/26573555/316de45d-6c47-4991-bf19-df139bfffea4)
... into landscape mode:
![B6D9F13F-D187-4FE5-9D0E-A6CF64DF9AD6_1_201_a](https://github.com/docusealco/docuseal/assets/26573555/cb755998-6393-4fad-bb68-74129e4c6a67)

Maybe there is a way to overcome this issue or provide a small info-text or something related. I would also appreciate a way to overcome this case and provide a workaround for my clients. However, it is clearly a corner case, but especially elderly people are used to do this and get confused.

Thanks in advance!

Cheers,
Leo

**Comment by omohokcoj** [comment]
@estallio thanks for reporting this - we released a fix to always minimize form with fields on mobile landscape screen. Please reopen if the issue still persists.

**Comment by estallio** [comment]
Maybe this is also helpful when in portrait mode. The procedure I could observe was that people open the site and turn the phone for signing. This way, the issue still persists.
