### ISSUE TITLE
SMS is verified multiple times

### ISSUE THREAD

**Issue by estallio** [docusealco/docuseal#251]
Hi!

I played around with SMS verification. In my document, the SMS-field was somewhere in the middle. First, I filled out some other fields like name etc. Then I filled out the phone-field and verified my number. Next, I followed the filling process with the next-button and filled out the missing fields. At the end, I got redirected to the phone-field again which got cleared. Then I had to fill out and verify my number again to finish the signing process. In the audit-logs the SMS-verification step is also listed two times. Does this mean the phone-field has to be always the last one? Or can you somehow check if the SMS-verification has already been submitted before requesting it again?

Cheers,
Leo

**Comment by omohokcoj** [comment]
@estallio thanks for pointing this out - in the latest version we made it so that the phone field can be verified only once

**Comment by estallio** [comment]
Now, the SMS is skipped. My case: I have a web form. The user fills out the form and submits the date. I check the data and correct them. Afterwards, I send a link to the user that opens my website where a DocuSeal form is embedded. All fields are prefilled with the react component. All fields are read-only, except the phone field. The user can now click on signature and submit the form, without getting asked for the SMS. However, when manually selecting the phone-field and clicking on "Next", the number gets verified. The expected behavior is that the pre-filled phone number has to be verified and can not be skipped.

**Comment by omohokcoj** [comment]
@estallio thanks for reporting this - the issue has been fixed in the docuseal cloud, please let me know if everything works as expected.

**Comment by estallio** [comment]
Thank you for the quick fix. The form now jumps back to the phone number field. However, now the pre-fill of the phone number does not work as expected. The red bar in the PDF id empty but the pre-filled phone number is visible in the form field at the bottom. Additionally, I can not edit the number in the form field at the bottom and when I click on the red bar in the PDF, there is an error in the JS console. 
![image](https://github.com/docusealco/docuseal/assets/26573555/ceb65274-3ec8-4b72-879e-4c7d76f90618)

**Comment by omohokcoj** [comment]
@estallio the 422 is an expected error that is returned to let the front-end know that the phone is not verified yet.
That's true that with prefilled phone number it's not possible to edit it - does your use case require editing a phone number?

**Comment by estallio** [comment]
No, that is not the use case, but the form looks like this, which might be confusing:
![image](https://github.com/docusealco/docuseal/assets/26573555/28342fef-6cce-4764-ac2d-69189c886e81)

As you can see, the phone number in the red bar is missing, but is visible in the modal. When I click next, the phone number also appears in in the red bar in the PDF view.

**Comment by omohokcoj** [comment]
@estallio phone number appears in the box only after it was verified via the OTP

**Comment by estallio** [comment]
Ah I see. Thanks for the clarification and the fast response times - I appreciate your service!
