### ISSUE TITLE
What exactly are cells?

### ISSUE THREAD

**Issue by estallio** [docusealco/docuseal#252]
Hi!

I can't find information about cells, what they are for and how I should use them? Does it only divide the letter of a word?

PS: Is it similar to a table? Do you plan to add a similar thing like a table?

Cheers,
Leo

**Comment by omohokcoj** [comment]
@estallio cells field type is designed to fill PDF forms with cells:
![image](https://github.com/docusealco/docuseal/assets/5418788/b716c7ea-d26d-4e62-a82e-86ff0f06c78c)
Please reopen if you have any questions

**Comment by Ludevsoftware** [comment]
How to use it with api request?
