### ISSUE TITLE
Feature request: Create document in the app instead of uploading

### ISSUE THREAD

**Issue by bernhardmostrey** [docusealco/docuseal#255]
Would love to replace our PandaDoc with your app, however, uploading a docx file results in low quality PDF. Would to have an editor in the app so I can create simple templates.

Also, when creating a new document with a template, I'd like to be able to input some variables right away and then send the doc to the signee.

Just my thoughts ;)

**Comment by omohokcoj** [comment]
@bernhardmostrey thanks for the suggestions:

>uploading a docx file results in low quality PDF
PDF page image previews might seem low quality - but the signed PDF from the docx upload should be in the original quality 

>Would to have an editor in the app so I can create simple templates.
That's not a goal of the project at the moment

>Also, when creating a new document with a template, I'd like to be able to input some variables right away and then send the doc to the signee.

it's possible with docx - if you put {{signature}} text tag in the docx it will be automatically replaced with signature field:
https://www.docuseal.co/guides/use-embedded-text-field-tags-in-the-pdf-to-create-a-fillable-form
