### ISSUE TITLE
Install in Docker Desktop on Windows

### ISSUE THREAD

**Issue by sanderz19** [docusealco/docuseal#256]
Hello,

I tried installing DocuSeal on my Windows machine with Docker Desktop using the following command in Windows PowerShell: "docker run --name docuseal -p 3000:3000 -v.:/data docuseal/docuseal". It pull a number of files/packages, and created the container. Unfortunately, it gave me the following error: 

"(HTTP code 400) unexpected - failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: mkdir /data/docuseal: permission denied: unknown"

Please advise.

Thank you!

**Comment by omohokcoj** [comment]
@sanderz19 did you try to run with sudo?

**Comment by sanderz19** [comment]
Yes, "sudo" doesn't appear to be a command recognized by PowerShell. It only installs the Docker container for me without "sudo".  Thanks

**Comment by mghabdo** [comment]
@sanderz19  try to create this directory manually :  `/data/docuseal`   by accessing into the docker container
