### ISSUE TITLE
All text input fields are getting hit with "Please match the requested format"

### ISSUE THREAD

**Issue by lehleh** [docusealco/docuseal#258]
The only ways I can submit my forms now is either setting the fields optional, or clicking "Toggle Multiline Text" and then clicking next/submit.

**Comment by omohokcoj** [comment]
@lehleh does it happen in open-source self-hosted or Cloud ?

**Comment by lehleh** [comment]
@omohokcoj it's happening on cloud

**Comment by omohokcoj** [comment]
@lehleh which browser are you using - can you please share a screenshot if your text field with data and error message?

**Comment by lehleh** [comment]
Issue happening on Chrome 

![image](https://github.com/docusealco/docuseal/assets/24360964/33574a45-4018-4703-8d68-77241e0bcedb)
![image](https://github.com/docusealco/docuseal/assets/24360964/52943be6-b014-4ec2-bde7-d78b10538963)
![image](https://github.com/docusealco/docuseal/assets/24360964/37a2a46f-b137-4e70-9510-6b7d2f613203)

I just restarted my chrome and the validation error doesn't show up anymore. Sorry wasn't able to reproduce it consistently but I have tested with Firefox and no error. I'll close the issue for now.

Thank you for the swift response <3
