### ISSUE TITLE
Real-world identity: Add ID.me for OAuth

### ISSUE THREAD

**Issue by aodhan-domhnaill** [docusealco/docuseal#265]
ID.me verifies signers with real-world identity https://www.id.me/. DocuSign has a binding, but Docusign documentation is terrible and I don't know how to use this https://help.id.me/hc/en-us/articles/10929304238999-DocuSign-and-ID-me.

For certain legal contracts, it would be very powerful to a strong tie to ID.me.

Looks like this could be done by following this https://github.com/docusealco/docuseal/commit/9f48c6e62536fa5ea61e46d3b07d9cb816745712.

https://developers.id.me/documentation

**Comment by omohokcoj** [comment]
@aodhan-domhnaill thanks for the suggestion - unfortunately i think it's not technically viable for open-source self-hosted app

**Comment by aodhan-domhnaill** [comment]
Ok. You already have SSO with Google and Microsoft though. An immediate upgrade would be to include SSO info in the signature.
