### ISSUE TITLE
[Feature Request] Thousands Separator for Number Type

### ISSUE THREAD

**Issue by austinm911** [docusealco/docuseal#268]
Pretty self explanatory. Would useful as I am considering using a text type to display a purchase price but if I upgrade to Pro down the road, then that wouldn't work with formulas. 

For a purchase price on a contract, it's much easier to accidentally mis-enter the price without the thousands separator to easily see the price is incorrect.

**Comment by omohokcoj** [comment]
@austinm911 thousands separator format options were added in the 1.5.6 version
![image](https://github.com/docusealco/docuseal/assets/5418788/73b8f13e-a293-4406-abaf-dcbb325f9006)
