### ISSUE TITLE
Blank Submission page allowed

### ISSUE THREAD

**Issue by jacobburrell** [docusealco/docuseal#276]
When making a new `Document Template` you can attempt to `Sign it yourself` despite having not uploaded any document/template.

After providing your email when signing it yourself, a blank screen will show. 

<img width="1664" alt="image" src="https://github.com/docusealco/docuseal/assets/61520543/2f61055c-5281-4ba2-a55b-fa0b7e394297">

This page should never be shown. Either require the document to be uploaded before submission by redirecting/notifying the user, or do not offer the ability to create a submission until a document has been uploaded.

**Comment by omohokcoj** [comment]
@jacobburrell thanks for reporting this, there is a message when the user tries to save/submit an empty template - that's true that the user can just close the editor page and navigate to the template page, i think additional error messages are not necessary  in this case.

![image](https://github.com/docusealco/docuseal/assets/5418788/0ede6f3a-5435-4b27-a868-b5c278725db4)
