### ISSUE TITLE
No option to Sign yourself if document has existing submission

### ISSUE THREAD

**Issue by jacobburrell** [docusealco/docuseal#277]
When first creating a document, the useful option to `Sign it yourself` exists. However, when there exists an invite or submission, there is no button or method to `sign it yourself`.

<img width="505" alt="image" src="https://github.com/docusealco/docuseal/assets/61520543/6bcc5fdf-dd57-4e9c-94bd-b1d919455ef5">

<img width="1217" alt="image" src="https://github.com/docusealco/docuseal/assets/61520543/1a9aec0e-b937-4cb6-bdab-5bb98a99b352">

**Comment by omohokcoj** [comment]
@jacobburrell there is sign yourself option on the edit template page
/templates/id/edit
