### ISSUE TITLE
 After HOST in .env is changed, submitter.link in emails continue to use old HOST url base

### ISSUE THREAD

**Issue by spanjeta** [docusealco/docuseal#283]
After HOST in .env is changed, submitter.link in emails continue to use old HOST url base
Tested on clean docker Image using version v1.5.8 . 
this issue is happening 100 percent.

First setup  using docker compose with HOST1. And after testing some documents, change host to HOST2  and restart docker containers.

**Comment by omohokcoj** [comment]
@spanjeta update your app URL on /settings/account
