### ISSUE TITLE
[Feature Request] Input Validation for Text and Numbers

### ISSUE THREAD

**Issue by iwm911** [docusealco/docuseal#286]
Hi,

great project, thank you!

it would be nice if its possible to validate the input fields of text and numbers against a regex for example so i can create validation for my SSN fields or Phone number field for example.

Thanks

**Comment by omohokcoj** [comment]
@iwm911 field validation has been release in the 1.6.1 version
![image](https://github.com/docusealco/docuseal/assets/5418788/2ac01282-c1e7-4cb3-8e41-49484e6b3014)
