### ISSUE TITLE
[Feature Request] Allow grouping of fields to allow conditions by groups

### ISSUE THREAD

**Issue by iwm911** [docusealco/docuseal#288]
Hi,

It could be very beneficiary to enable the grouping of fields so that in forms which have 2 paths of filling (for example bank account vs credit card) it will be possible to group fields of one payment method and make them available only if that payment method is selected.

now the condition should be done individually per field.

**Comment by omohokcoj** [comment]
@iwm911 conditional fields are available in Pro
https://www.docuseal.co/resources/add-conditional-fields

**Comment by iwm911** [comment]
Hi,

It's true that conditional fields are available in pro, however grouping of fields and then apply a condition per group is not available.

**Comment by omohokcoj** [comment]
@iwm911 instead of grouping - the same condition can be applied to multiple fields

**Comment by iwm911** [comment]
Yes, but for multiple fields that could be a tidies task.

It's a nice to have feature that could save time.

**Comment by omohokcoj** [comment]
@iwm911 thanks for your suggestion - that's true that grouped fields might save time - but i think for now adding the same condition to multiple fields is the best option given the level of complexity groups can introduce both from the code and UI/UX pov.

**Comment by iwm911** [comment]
Ok, i guess it's understandable.

is it something you are open to get as a PR (given that conditions are a Pro feature)?

**Comment by omohokcoj** [comment]
@iwm911 unfortunately we do accept contributions for features which are the part of Pro (also it's unlikely we could have accepted it because of the complexity)
