### ISSUE TITLE
[BUG] Hidden Fields Still Show Up on Completed Document

### ISSUE THREAD

**Issue by RyanWolf01** [docusealco/docuseal#291]
Hello, I made a rule in DocuSeal where I would only see certain fields if a radio button was set to a certain selection. For example, let's say the user selects choice 1 on the radio input , fills out more form fields corresponding to choice 1, but then realizes they made a mistake and meant to choose choice 2. If they go back and change it to choice 2, all the fields corresponding to choice 1 will disappear in the UI. However, on form submission, all the writing corresponding to choice 1 will still be there and it causes a mess. 

IMO in cases where an element only exists conditionally, if that element is emitted and then the condition is no longer met, the contents of that element should be deleted.

<img width="878" alt="image" src="https://github.com/docusealco/docuseal/assets/72532718/a07769b4-23cd-4bec-8004-94e3f0715cb8">

**Comment by omohokcoj** [comment]
@RyanWolf01 thanks for reporting this - the issue has been fixed in the Cloud, please let me know if everything works as expected now.

**Comment by omohokcoj** [comment]
closing as fixed
