### ISSUE TITLE
Your account is not activated yet

### ISSUE THREAD

**Issue by dandaka** [docusealco/docuseal#292]
Hey DocuSeal team!

I can't get through the registration phase. When I try to log in, I see this message "Your account is not activated yet.". There is nothing I can do about it.

Does the service expect me to click a link in the email? I don't think I get those. And also error message should
1/ say that explicitly
2/ have ability to resend verification email
 
![not-activated](https://github.com/docusealco/docuseal/assets/2384694/d11a325f-a9a9-46a2-aabc-3ad428716da9)

**Comment by omohokcoj** [comment]
@dandaka could you please reach out support@docuseal.co with your email you're using to log in? (closing the issue since you probably don't want to publicly share your email on GH issues)

**Comment by dandaka** [comment]
support is not responding for 2 days, is it expected?

**Comment by evokelektrique** [comment]
Same issue, sent an support email, hope it'll get fixed soon
