### ISSUE TITLE
Grouping for checkboxes. 

### ISSUE THREAD

**Issue by NuttCorp** [docusealco/docuseal#30]
The scenario is we have setup a form with about 120 check boxes with no other field types in-between. The way docuseal tries to display this is all check boxes between any other type of field are grouped together and in my situation are overflowing the screen to the top. There are natural breaks in my form but nothing to fill out. I can force it to group properly by adding another field type like text box in between groups but there is no data needed for these and have to be skipped by the user. If there is a separator object that could trigger this or an option on the checkbox.
![DocuSeal__Open_Source_Document_Filling_and_Signing-20230727-220436](https://github.com/docusealco/docuseal/assets/34084918/e42c5b0c-110b-43cd-a412-7a1e8e156c8d)

**Comment by AlexandrToorchyn** [comment]
@NuttCorp Will be fixed in the next release

**Comment by AlexandrToorchyn** [comment]
@NuttCorp Let me know if the latest release (1.0.7) fixes this issue for you

**Comment by NuttCorp** [comment]
Yes. Now the height of the input dialog is limited and the content scrolls. Still no grouping exactly but this is reasonable and adequate solution. Thanks for the quick response.
