### ISSUE TITLE
remove github stars badge or allow header customization

### ISSUE THREAD

**Issue by meonkeys** [docusealco/docuseal#302]
DocuSeal is amazing. Easy to install, fast, clean, works well. Thank you!

Are the current maintainers open to the idea of removing the GitHub badge? I'd rather my self-hosted DocuSeal does not ping GitHub on every page hit. I think other DocuSeal self-hosters might prefer this as well (please thumbs up/down this issue to indicate support/dissent for the idea). Alternatively, maybe we allow customization of the header since some folks might want to rebrand / OEM / white label DocuSeal.

**Comment by omohokcoj** [comment]
Hi @meonkeys white label is the part of DocuSeal Pro self-hosted: https://www.docuseal.co/pricing
We're not planning to make branding/whitelabel in the free open-source version of the app.

**Comment by meonkeys** [comment]
Understood. Would you entertain a patch for this?

**Comment by omohokcoj** [comment]
@meonkeys customizations to the header/logo and GH badge removal is already available in Pro

**Comment by meonkeys** [comment]
Indeed, thanks, I saw you mentioned that above. Sounds like the answers are "no" to my original issue and "no" to a PR that did either, since these are part of the Pro product. Let me know if I got that wrong. I'll close this. Thanks for all your replies, @omohokcoj

**Comment by meonkeys** [comment]
Related: #143

**Comment by sistein** [comment]
I would also prefer to have the GitHub call removed... Especially if it is this useless.
