### ISSUE TITLE
SMTP SSL Error

### ISSUE THREAD

**Issue by 0nano** [docusealco/docuseal#304]
![image](https://github.com/docusealco/docuseal/assets/35236525/ed3ebeb3-075f-4f32-8d89-4d385fe80696)

I'm trying to connect to my Stalwart mail server but I get this error and I can't send anything.
I am also trying to use other ports 465 and 25, but this time I get this error.

![image](https://github.com/docusealco/docuseal/assets/35236525/3ce36154-3019-4a8a-a298-9441c9fb6611)

**Comment by omohokcoj** [comment]
@0nano could you please share a screenshot of your SMTP configs form?
Also try to set Security to Auto

**Comment by 0nano** [comment]
![image](https://github.com/docusealco/docuseal/assets/35236525/00ddb533-8880-425b-8645-37fb874a4d8f)
The error is the same for 587 and 25 port with security set to auto, but with 465 port the connection does not work and shows TCP Time Out.

**Comment by omohokcoj** [comment]
@0nano 465  is the port you should probably use - maybe SMTP ports are blocked by your server firewall.
Can you verify that SMTP works on your server inside docker - with curl or other app that uses SMTP?

**Comment by 0nano** [comment]
Ok, I have managed to connect to my mail server.I need to use the container name to use the Docker DNS to make the connection work.Before I only tested with the container IP, I think the parsing might not work well with the private IP in this case.

I tested inside the container, the connection with IP and container name both work well, just to add more detail I use openssh to try the connection.
