### ISSUE TITLE
Docuseal Unable to Identify Fields in CPAA.pdf Despite HexaPDF Command Line 

### ISSUE THREAD

**Issue by aroop** [docusealco/docuseal#313]
**Description:**
When attempting to process the file CPAA.pdf with Docuseal, the application fails to identify the fields within the document. However, using the HexaPDF library directly via the command line, the fields are correctly identified and printed. This discrepancy suggests a possible integration issue between Docuseal and the HexaPDF library.

**Expected Behavior:**
Docuseal should correctly identify and display the fields in CPAA.pdf as the HexaPDF command line tool does.

**Actual Behavior:**
Docuseal fails to identify any fields in CPAA.pdf, showing an empty or incorrect field list.

[CPAA.pdf](https://github.com/user-attachments/files/16165201/CPAA.pdf)

**Comment by omohokcoj** [comment]
Hi @aroop thanks for reporting this - it has been fixed in the Cloud and will be fixed in the new self-hosted version on Monday.

**Comment by aroop** [comment]
@omohokcoj I quickly tested this locally and seems like this issue is not yet fixed. I will retest it once the new version of self hosted drops next Monday

**Comment by aroop** [comment]
Verified this is fixed now. Thanks a lot for the quick fix
