### ISSUE TITLE
[Feature Request]

### ISSUE THREAD

**Issue by landoncrabtree** [docusealco/docuseal#320]
Ability for `HOST` to contain paths, for example `HOST=test.example.com/docuseal`. I'm wanting to use nginx to route `/docuseal` requests via `proxy_pass` to the docuseal container, however, the way that docuseal is setup, all paths use absolute paths. So, for example, 

`HOST=test.example.com/docuseal`
Still, redirects throughout the website drop the `/docuseal`.

**Comment by omohokcoj** [comment]
@landoncrabtree thanks for the suggestion, unfortunately that's not something we envision supporting in the foreseeable future.
To use multiple apps on the same host/reverse proxy subdomains is the only options at the moment.
