### ISSUE TITLE
Meaning of "Reason" in signature ID field?

### ISSUE THREAD

**Issue by EduNetEurope** [docusealco/docuseal#344]
The field below the signatures has:
- ID
- Reason
- Date

What exactly does "reason" mean here?

**Comment by omohokcoj** [comment]
@EduNetEurope signing "reason" is a part of the esignature requirements for certain industries - it can be customized when the 'reason' toggle is enabled in the settings
![image](https://github.com/user-attachments/assets/087c7269-42df-45a2-8f81-0b61d4853335)

**Comment by EduNetEurope** [comment]
The word "reason" appears even if the toggle is set to off.

**Comment by EduNetEurope** [comment]
Shouldn't it only appear if a signing reason is given?
