### ISSUE TITLE
App URL via env variable

### ISSUE THREAD

**Issue by gramakri** [docusealco/docuseal#348]
Hi,
I am the maintainer of the docuseal package for Cloudron (https://git.cloudron.io/cloudron/docuseal-app) .

This is loosely related to the SMTP config issue at https://github.com/docusealco/docuseal/issues/113 .

It seems the App URL is stored encrypted in the database. This makes it difficult to change the location of the app . i.e if the packages deployment URL changes, the app package cannot change the App URL automatically .

I guess we can write some script to decrypt and store it back but I was wondering if it's possible to store the App URL unencrypted in the first place. Alternately, like the SMTP vars maybe App URL can be picked from an env variable?

Thanks!

**Comment by omohokcoj** [comment]
@gramakri we've added the APP_URL=https://some-app.cloudron.io ENV variable in the new 1.7.0 release - please let me know if it solves the issue

**Comment by gramakri** [comment]
@omohokcoj thanks for the quick turnaround! Tested this now. While the value is getting picked up, the UI still shows the old value. I changed the domain from test to test2, the URL remains as test.

![image](https://github.com/user-attachments/assets/5c2f8582-f6c5-4fff-aeb6-d09613e6bf6b)

From what I can tell, the value in the database is not updated based on APP_URL. I think in the case of SMTP vars,  the values are in config . Whereas for URL, it's in the database (so, something has to update the old value).

**Comment by omohokcoj** [comment]
@gramakri yep - the value in the database is not updated based on the ENV vars - DB configs are just ignored when you have ENV vars specified

**Comment by gramakri** [comment]
@omohokcoj ah I see. The App URL in the UI keeps showing the old one though even if it's using the new one :thinking: Maybe it can be hidden like the SMTP settings?

**Comment by omohokcoj** [comment]
@gramakri we will hide the URL input in the next release

**Comment by omohokcoj** [comment]
@gramakri app url env var has been added

**Comment by gramakri** [comment]
@omohokcoj thanks! we will update our package.
