### ISSUE TITLE
the receipient field value will be changed after submitted.

### ISSUE THREAD

**Issue by unchannam** [docusealco/docuseal#352]
hello,

When I write email like "xyz@test.local.mo", it will change to "xyz@test.local.com" in receipient field after submitted.
how should I do to to eliminate this problem? thanks.

I am using docuseal latest version deployed via docker.

**Comment by Zuline** [comment]
> hello,
> 
> When I write email like "[xyz@test.local.mo](mailto:xyz@test.local.mo)", it will change to "[xyz@test.local.com](mailto:xyz@test.local.com)" in receipient field after submitted. how should I do to to eliminate this problem? thanks.
> 
> I am using docuseal latest version deployed via docker.

I'm having this exact same issue. Is there any update on this?

**Comment by omohokcoj** [comment]
@Zuline it should be fixed in the latest 1.7.5 version
