### ISSUE TITLE
Duplicate E-Mail Delivery

### ISSUE THREAD

**Issue by l4rm4nd** [docusealco/docuseal#365]
Unsure whether I have tracked down the actual issue.

However, if someone completes a form, I receive the notification e-mail about completion two times.

I assume this happens as e-mail notifications are enabled/configured at two different areas:

- Within Docuseal's notification settings at `/settings/notifications` > `Receive notification emails on completed submission` > Enabled/Checked
- Within the preferences of a form itself at `/templates/<ID>` > `Completed notification email` > Configured + Enabled

If I disable the e-mail notifications at `/settings/notifications`, I only receive one e-mail.

Is this behaviour as designed or a bug?

**Comment by omohokcoj** [comment]
@l4rm4nd the completion notification email is always sent to the signature requester user if the toggle is turned on.
Looks like you've added the same user email in the additional BCC addresses input - which resulted in two emails being sent

**Comment by l4rm4nd** [comment]
Indeed!

I have defined the same email address as BCC in the notification settings. What a fail.

Sorry for the issue creation!
