### ISSUE TITLE
Embedded text field tags in uploaded PDFs do not auto populate fields 

### ISSUE THREAD

**Issue by GlitchWitch** [docusealco/docuseal#367]
## Problem

When uploading a PDF that contains [embedded text field tags](https://www.docuseal.co/guides/use-embedded-text-field-tags-in-the-pdf-to-create-a-fillable-form#embedded-pdf-field-text-tags) using the Web UI the fields do not appear in the UI sidebar.

[Screencast from 2024-09-24 21-13-58.webm](https://github.com/user-attachments/assets/3bf18bb4-2989-4447-8e46-7ed65aee798d)

## Solution

Ensure that documents uploaded from the web UI are parsed properly so that fields can be assigned to.

## Additionally information

Tested using the [fieldtags.pdf](https://www.docuseal.co/examples/fieldtags.pdf) example on the Cloud Pro plan.

**Comment by omohokcoj** [comment]
@GlitchWitch embedded text fields are designed for the API but not for the web UI - use POST /templates/pdf to upload PDFs with embedded fields.

If you want to parse those fields in the web UI which can be useful for debugging - add `_tagged.pdf` suffix to the file name.
