### ISSUE TITLE
Docuseal signing email sent to junk

### ISSUE THREAD

**Issue by kbkozlev** [docusealco/docuseal#376]
Pretty much the titles.
The confirmation e-mail works, but the one requesting a signature gets sent to spam.

**Comment by omohokcoj** [comment]
@kbkozlev does the email sent from the Cloud info@docuseal.co email goes to spam or the email sent from your self-hosted app and SMTP?

**Comment by kbkozlev** [comment]
Hi @omohokcoj No the official email does not go to spam as far as I know, only the self hosted instance. But also not all e-mails from the self hosted - only the one requesting signature, all others work just fine.

**Comment by omohokcoj** [comment]
@kbkozlev try to change the name of your template to make it shorter or remove the template name form the email subject line.
Closing the issue since it's not related to the app but to your SMTP/domain email reputation and content
