### ISSUE TITLE
Dockerfile not building

### ISSUE THREAD

**Issue by nbulusanjr** [docusealco/docuseal#387]
![image](https://github.com/user-attachments/assets/e273cebe-a21b-4c85-8204-1da2ac8b72fc)

 > [webpack 15/15] RUN echo "gem 'shakapacker'" > Gemfile && ./bin/shakapacker:
': No such file or directorysr/local/bin/ruby

Environment: 
Windows 11 Pro 23H2
Docker version 27.3.1, build ce12230

**Comment by omohokcoj** [comment]
Hi @nbulusanjr try to run the pre-build docker image from https://hub.docker.com/r/docuseal/docuseal
Also we have docker run instructions here: https://www.docuseal.com/install
Unfortunately we can't provide support for custom/modified docker builds
