### ISSUE TITLE
Template API - Radio Buttons

### ISSUE THREAD

**Issue by johnhatch** [docusealco/docuseal#397]
Hi there, I am using the [templates api](https://www.docuseal.com/docs/api#create-a-template-from-existing-pdf) to create documents from an existing PDF, and using the `fields` property for placing fields. Radio is listed an accepted type in the docs, however it does not seem that the `options` property is accepted, so radio does not currently seem possible. Example request:

```json
"fields": [
  {
    "name": null,
    "role": "Customer",
    "type": "radio",
    "areas": [
      {
        "x": 42.59,
        "y": 93.39,
        "w": 34.08,
        "h": 11.36,
        "page": 1,
        "option_uuid": "12345a"
      },
      {
        "x": 42.59,
        "y": 107.54,
        "w": 36.92,
        "h": 11.36,
        "page": 1,
        "option_uuid": "12345b"
      },
      {
        "x": 42.599,
        "y": 121.69,
        "w": 34.08,
        "h": 11.36,
        "page": 1,
        "option_uuid": "12345c"
      }
    ],
    "options": [
      {
        "value": "test a",
        "uuid": "12345a"
      },
      {
        "value": "test b",
        "uuid": "12345b"
      },
      {
        "value": "test c",
        "uuid": "12345c"
      }
    ]
  },
  {
    "name": "Customer Signature",
    "role": "Customer",
    "type": "signature",
    "areas": [
      {
        "x": 42.599,
        "y": 636.75,
        "w": 266.96,
        "h": 17.04,
        "page": 1
      }
    ]
  }
]
```

It creates the field but with the options unexpectedly undefined it causes an error during signing:

![image](https://github.com/user-attachments/assets/5cf8ffdb-c5cf-4581-b11b-4d1d2f3962c6)

Thank you for your time!

**Comment by omohokcoj** [comment]
@johnhatch could you please try to pass 'option': 'string' value in the areas: [] array object:
https://www.docuseal.com/docs/api#create-a-template-from-existing-pdf.documents.fields.areas.option (the doc has been updated recently)

**Comment by johnhatch** [comment]
Can confirm this works perfectly. Thanks so much for the quick response!
