### ISSUE TITLE
[Feature Request] Disable uploading a signature

### ISSUE THREAD

**Issue by omar-al-ismaili** [docusealco/docuseal#404]
I'd like to have the possibility to disable uploading an image in the signature field similar to `data-allow-typed-signature="false"`. I checked the documentation and couldn't find a way to do it.

**Comment by omohokcoj** [comment]
@omar-al-ismaili @mark-addams001881 it's already possible to configure via signature settings https://www.docuseal.com/resources/accept-only-drawn-signatures

**Comment by omar-al-ismaili** [comment]
@omohokcoj, how to specify this when creating a document using the API?

**Comment by omohokcoj** [comment]
@omar-al-ismaili in the fields: [] array where you have your signature field - pass format: 'drawn'
