### ISSUE TITLE
Signature validation with ADOBE ACROBAT

### ISSUE THREAD

**Issue by fdecourt** [docusealco/docuseal#47]
Hi,
There is a message on ADOBE ACROBAT saying that there is a problem with the signature : 
![image](https://github.com/docusealco/docuseal/assets/4050977/8468fa62-bd44-48fc-bacb-e2d31eb8eeca)

![image](https://github.com/docusealco/docuseal/assets/4050977/7fe8f47c-1271-4646-af8e-d8e066a741bd)

Regards,

**Comment by AlexandrToorchyn** [comment]
@fdecourt Basically Adobe Acrobat reader just says that the document has been signed with a non-trusted certificate (self-signed).
Trusted certificates are pricey https://www.sslmarket.com/ssl/aatl-certificates-for-trusted-pdf-signing/ - users that self host Docuseal don't have those certificates.

But in terms of any practical use - I believe this green trusted certificate checkmark in acrobat reader doesn't make any sense.

A self-signed document with an autogenerated certificate can be verified via the /settings/esign page - also the signature ensures that the document hasn't been altered afterwards.

**Comment by fdecourt** [comment]
Hi,
Thanks for this information. Effectively this is probably useless.
Regards,

**Comment by cmantsch** [comment]
@AlexandrToorchyn But would it be possible to intergrate such a trusted certificate if I'm willing to pay the price?
I recently stumbled over DocuSeal and since we are currently evaluating different signature softwares for the company I work at this might also be an option (given it is possible)
