### ISSUE TITLE
Share link document displays empty page

### ISSUE THREAD

**Issue by Silur** [docusealco/docuseal#51]
Viewing the share link of a populated document results with the following screen:

![image](https://github.com/docusealco/docuseal/assets/3187667/b547b875-1cc2-49b3-9b8f-06eee0ea39de)

Steps to reproduce:
- Self-host docuseal with docker-compose
- Upload and populate PDF
- Copy share link
- View share link

Tried in multiple browsers with `--safe-mode` (no plugins and empty cache)

Console shows an error on `form.vue:392`:

```
TypeError: this.currentStepFields is undefined
    currentField form.vue:392
```

**Comment by AlexandrToorchyn** [comment]
@Silur Please make sure your storage is configured correctly
