### ISSUE TITLE
Modified AGPL License Terms

### ISSUE THREAD

**Issue by 3brover005** [docusealco/docuseal#56]
It seems that you have added additional restrictions to the AGPL license applied to this repository. Adding additional restrictions (the wording at the top of the license) are in direct contradiction with the AGPL license, in particular with the following statement:

All other non-permissive additional terms are considered "further
restrictions" within the meaning of section 10.  If the Program as you
received it, or any part of it, contains a notice stating that it is
governed by this License along with a term that is a further
restriction, you may remove that term.

So it seems that you have either just made DocuSeal Enterprise closed source - i.e. no longer AGPL - or you've made a mistake and accidentally added restrictions to it, which can be removed according to the AGPL license. You can see this from the fact that Github automatically removed the AGPL license tag against the repository..

I am pretty sure the community would like to know what is going on with this, as you are misguiding the community and it is not fair to committers of the project. 

After all, AGPL and the like OSS licenses are created to be easily understood and interpreted by standardising the different licensing models, all in the effort to encourage the truly open and free nature of software for the greater good. In this case, I believe you are adding restrictions and no longer making this an Open Source project, in the name of profiting from this application and intentionally curbing community collaboration.

Please elaborate

**Comment by AlexandrToorchyn** [comment]
@3brover005 

>So it seems that you have either just made DocuSeal Enterprise closed source - i.e. no longer AGPL

DocuSeal Enterprise doesn't exist - there is only one DocuSeal AGPL public repository.

>I am pretty sure the community would like to know what is going on with this, as you are misguiding the community and it is not fair to committers of the project.

I'm the only committer of the project so far :)

New additional terms are basically very similar to the HexaPDF terms - they are designed to protect the project from companies that want to reuse it in their commercial software without contribution anything into open-source.
