### ISSUE TITLE
Can't configure SMTP sending (GMail)

### ISSUE THREAD

**Issue by maaper** [docusealco/docuseal#74]
Dear all,
I have an instance of DOCUSEAL running on my Synology NAS in one docker container.
It seems to work properly, but I'm not able to send any email.
I have the two-factor authentication method on my Gmail account. I properly configure and obtain an app password.

Then I configured Docuseal as follow:
- Host: smtp.gmail.com
- Port: 465
- Username: my Google account
- Password: my generated APP Password (copy-pasting it)
- Send from mail: same than username

The issue is that im not able to send any mail, but I also not receiving any error message, so it's not possible for me to investigate deeply what can be wrong.

Thanks in advance. 
I used those guides for the installation:
https://mariushosting.com/how-to-install-docuseal-on-your-synology-nas/
https://mariushosting.com/synology-set-up-email-notifications-on-docuseal/

**Comment by mariushosting** [comment]
I can't replicate this issue on different DocuSeal Instances. Everything is working like a charm on my end.

**Comment by maaper** [comment]
I tried to create a new user (email it supposed to be send to the user) so I can get some log with the hope of someone can help me to identify the issue.


`2023-08-08T14:27:09.969742308Z I, [2023-08-08T14:27:09.969446 #1]  INFO -- : [90288fc8-fa5e-43f1-a4df-c748447827bc] [ActiveJob] Enqueued ActionMailer::MailDeliveryJob (Job ID: 78c423fd-d7b8-4a9d-8270-4dd1a9428f1f) to Async(default) with arguments: "UserMailer", "invitation_email", "deliver_now!", {:args=>[#<GlobalID:0x00007fefccde9630 @uri=#<URI::GID gid://docu-seal/User/3>>]}`

`2023-08-08T14:27:09.971400683Z I, [2023-08-08T14:27:09.971217 #1]  INFO -- : [90288fc8-fa5e-43f1-a4df-c748447827bc] {"method":"POST","path":"/users","format":"turbo_stream","controller":"UsersController","action":"create","status":302,"duration":105.01,"view":0.0,"db":21.72,"location":"https://docuseal.cnlb.es/settings/users","fwd":"172.19.0.1"}`

`2023-08-08T14:27:09.974817777Z I, [2023-08-08T14:27:09.974603 #1]  INFO -- : [ActiveJob] [ActionMailer::MailDeliveryJob] [78c423fd-d7b8-4a9d-8270-4dd1a9428f1f] Performing ActionMailer::MailDeliveryJob (Job ID: 78c423fd-d7b8-4a9d-8270-4dd1a9428f1f) from Async(default) enqueued at 2023-08-08T14:27:09Z with arguments: "UserMailer", "invitation_email", "deliver_now!", {:args=>[#<GlobalID:0x00007fefcce3a828 @uri=#<URI::GID gid://docu-seal/User/3>>]}`

`2023-08-08T14:27:10.050507599Z I, [2023-08-08T14:27:10.050292 #1]  INFO -- : [e8275cb4-0362-48af-a7cd-8a0660120be2] {"method":"GET","path":"/settings/users","format":"turbo_stream","controller":"UsersController","action":"index","status":200,"duration":14.7,"view":8.06,"db":1.64,"fwd":"172.19.0.1"}`

`2023-08-08T14:27:15.030262938Z E, [2023-08-08T14:27:15.029902 #1] ERROR -- : [ActiveJob] [ActionMailer::MailDeliveryJob] [78c423fd-d7b8-4a9d-8270-4dd1a9428f1f] Error performing ActionMailer::MailDeliveryJob (Job ID: 78c423fd-d7b8-4a9d-8270-4dd1a9428f1f) from Async(default) in 5059.9ms: Errno::EADDRNOTAVAIL (Address not available - connect(2) for [2a00:1450:4025:402::6c]:465):`

`2023-08-08T14:27:15.030767654Z /usr/local/lib/ruby/3.2.0/socket.rb:1217:in `__connect_nonblock'`

`2023-08-08T14:27:15.030813550Z /usr/local/lib/ruby/3.2.0/socket.rb:1217:in `connect_nonblock'`

`2023-08-08T14:27:15.030845609Z /usr/local/lib/ruby/3.2.0/socket.rb:60:in `connect_internal'

`2023-08-08T14:27:15.030879585Z /usr/local/lib/ruby/3.2.0/socket.rb:141:in `connect'

`2023-08-08T14:27:15.030908898Z /usr/local/lib/ruby/3.2.0/socket.rb:645:in `block in tcp'

`2023-08-08T14:27:15.030939584Z /usr/local/lib/ruby/3.2.0/socket.rb:231:in `each'

`2023-08-08T14:27:15.030969431Z /usr/local/lib/ruby/3.2.0/socket.rb:231:in `foreach'

`2023-08-08T14:27:15.030997366Z /usr/local/lib/ruby/3.2.0/socket.rb:635:in `tcp'

`2023-08-08T14:27:15.031024972Z /usr/local/lib/ruby/gems/3.2.0/gems/net-smtp-0.3.3/lib/net/smtp.rb:643:in `tcp_socket'

`2023-08-08T14:27:15.031062007Z /usr/local/lib/ruby/gems/3.2.0/gems/net-smtp-0.3.3/lib/net/smtp.rb:656:in `do_start'

`2023-08-08T14:27:15.031092213Z /usr/local/lib/ruby/gems/3.2.0/gems/net-smtp-0.3.3/lib/net/smtp.rb:611:in `start'`

`2023-08-08T14:27:15.031122144Z /usr/local/bundle/gems/mail-2.8.1/lib/mail/network/delivery_methods/smtp.rb:109:in `start_smtp_session'`

`2023-08-08T14:27:15.031160176Z /usr/local/bundle/gems/mail-2.8.1/lib/mail/network/delivery_methods/smtp.rb:100:in `deliver!'`

`2023-08-08T14:27:15.031192916Z /usr/local/bundle/gems/mail-2.8.1/lib/mail/message.rb:269:in `deliver!'`

`2023-08-08T14:27:15.031223103Z /usr/local/bundle/gems/actionmailer-7.0.5/lib/action_mailer/message_delivery.rb:109:in `block in deliver_now!'`

`2023-08-08T14:27:15.031255641Z /usr/local/bundle/gems/actionmailer-7.0.5/lib/action_mailer/rescuable.rb:17:in `handle_exceptions'`

`2023-08-08T14:27:15.031286991Z /usr/local/bundle/gems/actionmailer-7.0.5/lib/action_mailer/message_delivery.rb:108:in `deliver_now!'`

`2023-08-08T14:27:15.031316288Z /usr/local/bundle/gems/actionmailer-7.0.5/lib/action_mailer/mail_delivery_job.rb:23:in `perform'`

`2023-08-08T14:27:15.031349540Z /usr/local/bundle/gems/activejob-7.0.5/lib/active_job/execution.rb:59:in `block in _perform_job'`

`2023-08-08T14:27:15.031380464Z /usr/local/bundle/gems/activesupport-7.0.5/lib/active_support/callbacks.rb:118:in `block in run_callbacks'`

`2023-08-08T14:27:15.031412751Z /usr/local/bundle/gems/i18n-1.14.1/lib/i18n.rb:322:in `with_locale'`

`2023-08-08T14:27:15.031447304Z /usr/local/bundle/gems/activejob-7.0.5/lib/active_job/translation.rb:9:in `block (2 levels) in <module:Translation>'`

`2023-08-08T14:27:15.031487786Z /usr/local/bundle/gems/activesupport-7.0.5/lib/active_support/callbacks.rb:127:in `instance_exec'`

`2023-08-08T14:27:15.031518041Z /usr/local/bundle/gems/activesupport-7.0.5/lib/active_support/callbacks.rb:127:in `block in run_callbacks'`

`2023-08-08T14:27:15.031547141Z /usr/local/bundle/gems/activesupport-7.0.5/lib/active_support/core_ext/time/zones.rb:65:in `use_zone'`

`2023-08-08T14:27:15.031585026Z /usr/local/bundle/gems/activejob-7.0.5/lib/active_job/timezones.rb:9:in `block (2 levels) in <module:Timezones>'`

`2023-08-08T14:27:15.031619120Z /usr/local/bundle/gems/activesupport-7.0.5/lib/active_support/callbacks.rb:127:in `instance_exec'`

`2023-08-08T14:27:15.031655170Z /usr/local/bundle/gems/activesupport-7.0.5/lib/active_support/callbacks.rb:127:in `block in run_callbacks'`

`2023-08-08T14:27:15.031689080Z /usr/local/bundle/gems/activesupport-7.0.5/lib/active_support/callbacks.rb:138:in `run_callbacks'`

`2023-08-08T14:27:15.031718758Z /usr/local/bundle/gems/activejob-7.0.5/lib/active_job/execution.rb:58:in `_perform_job'`

`2023-08-08T14:27:15.031748791Z /usr/local/bundle/gems/activejob-7.0.5/lib/active_job/instrumentation.rb:20:in `_perform_job'`

`2023-08-08T14:27:15.031779722Z /usr/local/bundle/gems/activejob-7.0.5/lib/active_job/execution.rb:46:in `perform_now'`

`2023-08-08T14:27:15.031808912Z /usr/local/bundle/gems/activejob-7.0.5/lib/active_job/instrumentation.rb:14:in `block in perform_now'`

`2023-08-08T14:27:15.031838316Z /usr/local/bundle/gems/activejob-7.0.5/lib/active_job/instrumentation.rb:25:in `block in instrument'`

`2023-08-08T14:27:15.031868902Z /usr/local/bundle/gems/activesupport-7.0.5/lib/active_support/notifications.rb:206:in `block in instrument'`

`2023-08-08T14:27:15.031899861Z /usr/local/bundle/gems/activesupport-7.0.5/lib/active_support/notifications/instrumenter.rb:24:in `instrument'`

`2023-08-08T14:27:15.031929992Z /usr/local/bundle/gems/activesupport-7.0.5/lib/active_support/notifications.rb:206:in `instrument'`

`2023-08-08T14:27:15.031958596Z /usr/local/bundle/gems/activejob-7.0.5/lib/active_job/instrumentation.rb:35:in `instrument'`

`2023-08-08T14:27:15.031988054Z /usr/local/bundle/gems/activejob-7.0.5/lib/active_job/instrumentation.rb:14:in `perform_now'`

`2023-08-08T14:27:15.032016188Z /usr/local/bundle/gems/activejob-7.0.5/lib/active_job/logging.rb:18:in `block in perform_now'`

`2023-08-08T14:27:15.032052777Z /usr/local/bundle/gems/activesupport-7.0.5/lib/active_support/tagged_logging.rb:99:in `block in tagged'`

`2023-08-08T14:27:15.032085456Z /usr/local/bundle/gems/activesupport-7.0.5/lib/active_support/tagged_logging.rb:37:in `tagged'`

`2023-08-08T14:27:15.032117826Z /usr/local/bundle/gems/activesupport-7.0.5/lib/active_support/tagged_logging.rb:99:in `tagged'`

`2023-08-08T14:27:15.032146368Z /usr/local/bundle/gems/activejob-7.0.5/lib/active_job/logging.rb:25:in `tag_logger'`

`2023-08-08T14:27:15.032175666Z /usr/local/bundle/gems/activejob-7.0.5/lib/active_job/logging.rb:18:in `perform_now'`

`2023-08-08T14:27:15.032204127Z /usr/local/bundle/gems/activejob-7.0.5/lib/active_job/execution.rb:24:in `block in execute'`

`2023-08-08T14:27:15.032235493Z /usr/local/bundle/gems/activesupport-7.0.5/lib/active_support/callbacks.rb:118:in `block in run_callbacks'`

`2023-08-08T14:27:15.032264648Z /usr/local/bundle/gems/activejob-7.0.5/lib/active_job/railtie.rb:54:in `block (4 levels) in <class:Railtie>'`

`2023-08-08T14:27:15.032296734Z /usr/local/bundle/gems/activesupport-7.0.5/lib/active_support/execution_wrapper.rb:92:in `wrap'`

`2023-08-08T14:27:15.032326712Z /usr/local/bundle/gems/activesupport-7.0.5/lib/active_support/reloader.rb:72:in `block in wrap'`

`2023-08-08T14:27:15.032359287Z /usr/local/bundle/gems/activesupport-7.0.5/lib/active_support/execution_wrapper.rb:92:in `wrap'`

`2023-08-08T14:27:15.032387614Z /usr/local/bundle/gems/activesupport-7.0.5/lib/active_support/reloader.rb:71:in `wrap'`

`2023-08-08T14:27:15.032416205Z /usr/local/bundle/gems/activejob-7.0.5/lib/active_job/railtie.rb:53:in `block (3 levels) in <class:Railtie>'`

`2023-08-08T14:27:15.032449143Z /usr/local/bundle/gems/activesupport-7.0.5/lib/active_support/callbacks.rb:127:in `instance_exec'`

`2023-08-08T14:27:15.032480767Z /usr/local/bundle/gems/activesupport-7.0.5/lib/active_support/callbacks.rb:127:in `block in run_callbacks'`

`2023-08-08T14:27:15.032510386Z /usr/local/bundle/gems/activesupport-7.0.5/lib/active_support/callbacks.rb:138:in `run_callbacks'`

`2023-08-08T14:27:15.032543438Z /usr/local/bundle/gems/activejob-7.0.5/lib/active_job/execution.rb:22:in `execute'`

`2023-08-08T14:27:15.032573430Z /usr/local/bundle/gems/activejob-7.0.5/lib/active_job/queue_adapters/async_adapter.rb:70:in `perform'`

`2023-08-08T14:27:15.032609818Z /usr/local/bundle/gems/concurrent-ruby-1.2.2/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:352:in `run_task'`

`2023-08-08T14:27:15.032648184Z /usr/local/bundle/gems/concurrent-ruby-1.2.2/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:343:in `block (3 levels) in create_worker'`

`2023-08-08T14:27:15.032684209Z /usr/local/bundle/gems/concurrent-ruby-1.2.2/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:334:in `loop'`

`2023-08-08T14:27:15.032717619Z /usr/local/bundle/gems/concurrent-ruby-1.2.2/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:334:in `block (2 levels) in create_worker'`

`2023-08-08T14:27:15.032750229Z /usr/local/bundle/gems/concurrent-ruby-1.2.2/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:333:in `catch'`

`2023-08-08T14:27:15.032782455Z /usr/local/bundle/gems/concurrent-ruby-1.2.2/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:333:in `block in create_worker'`
`

**Comment by maaper** [comment]
Looking at the log in detail, the error seems to be here, but I dont know how to solve.

````
E, [2023-08-08T14:44:36.053629 #1] ERROR -- : [ActiveJob] [ActionMailer::MailDeliveryJob] [3a31fe6f-1111-4321-8f4b-521b2ce18bb3] Error performing ActionMailer::MailDeliveryJob (Job ID: 3a31fe6f-1111-4321-8f4b-521b2ce18bb3) from Async(default) in 5072.58ms: Errno::EADDRNOTAVAIL (Address not available - connect(2) for [2a00:1450:4025:402::6d]:465):
````

**Comment by maaper** [comment]
I found the solution.
I don't know why but if I use port 587 instead of 465 on the configuration it works.


Thanks!!
