### ISSUE TITLE
PDF download has tiny text when stored in Azure

### ISSUE THREAD

**Issue by ATechAdventurer** [docusealco/docuseal#77]
When storing/downloading PDFs from Azure Storage, the text in the downloaded PDFs is tiny. This doesn't seem to happen when using local file storage.

**Comment by AlexandrToorchyn** [comment]
@ATechAdventurer Thanks for reporting the issue - the bug was caused by a large PDF page size (that's not related to Azure).
I've just pushed a fix into master - it will be available in the 1.1.1 release.

**Comment by ATechAdventurer** [comment]
Awesome, great work. Appreciate the quick turnaround.
