### ISSUE TITLE
Signature not stamped on PDF

### ISSUE THREAD

**Issue by 3brover005** [docusealco/docuseal#80]
Latest release seems to not stamp the signature on the pdf.

<img width="808" alt="image" src="https://github.com/docusealco/docuseal/assets/61079544/cac0afff-ed80-4224-917a-ef468c95222c">

Getting the following error when I click on the signature area above (after signing):
Uncaught (in promise) TypeError: Cannot read properties of null (reading 'querySelector'):

Code: this.$refs.form.querySelector('input[type="date"], input[type="text"], select')?.focus()

Looks like the $refs.form var is lost

**Comment by AlexandrToorchyn** [comment]
@3brover005 `this.$refs.form.querySelector('input[type="date"], input[type="text"], select')?.focus()` null reference error is not related to the signature upload and happens happens after mouse click on the signature field once the form is completed (that's a know error that has no impact on the user experience).

Missing signature might be related to your specific/custom docuseal setup/code. I was not able to reproduce this in the latest docker version.

**Comment by 3brover005** [comment]
You are right, the issue was with bad setup on our end. Thanks
