### ISSUE TITLE
Send the same document twice from the link [feature tequest]

### ISSUE THREAD

**Issue by maaper** [docusealco/docuseal#81]
We are a sports club, and this upcoming season, we are going to use Docuseal so that members can submit the necessary forms to obtain the federation license for their children. Initially, we will share the link on our internal Telegram channel for them to access the form.

The problem we have noticed is that if a member has two children, they can only submit the form once. When they try to submit it again after identifying themselves for the second child, the system doesn't offer the option to fill it out again; it simply indicates that it has already been submitted. 

Are you planning to enable this feature in an upcoming release?

In the meantime, we have noticed that if we send them a request to fill out the form via email, it allows them to access it (even with the same email). So, for now, we will use that method, although the previous one would be more convenient and logical for us. 😅

**Comment by AlexandrToorchyn** [comment]
@maaper We added this feature in the latest release (1.2.4)
