### ISSUE TITLE
Can you make fields mandatory?

### ISSUE THREAD

**Issue by maaper** [docusealco/docuseal#83]
### Discussed in https://github.com/docusealco/docuseal/discussions/73

<div type='discussions-op-text'>

<sup>Originally posted by **ovizii** August  8, 2023</sup>
I'm just going through my first tests with a self-hosted docuseal and I added a date and a signature field to a PDF and I was simply able to ignore the signature, fill in the date field and submit. 

Unless I am making a mistake somewhere, this does not seem to make sense to me.</div>

**Comment by AlexandrToorchyn** [comment]
@maaper 
> ignore the signature

That's true. It's possible to send a blank signature – just drawing a single dot on the canvas is enough to pass client-side validation. There are no simple ways to improve this, so we just rely on users adding their signatures as requested.

**Comment by maaper** [comment]
@AlexandrToorchyn I mean that when I receive the webhook I receive [blank] in the content of the signature within the json field. 

Even if the user enter a simple dot the code of the field going with the webhook will not be [blank] in the receiving json. 

In any case that is not happening to not with the field of sign, in some situations user can override the obligation of sending the form without filling all mandatory fields.

**Comment by omohokcoj** [comment]
It's possible to make fields required - with the new app version required fields are not skippable
That's true that just putting a dot in signature canvas is considered as signature and it allows users to submit it and proceed with other fields.
I think in this case the admin user can request them to resubmit their signature (ability to resubmit docs has been added in the 1.2.5 rversion)
