### ISSUE TITLE
Docuseal SSL issue behind HAPROXY

### ISSUE THREAD

**Issue by lucafolin** [docusealco/docuseal#86]
Hi, I'm running Docuseal docker container behind an HAPROXY only with these environmental variables:

- FORCE_SSL: true
- HOST: https://docuseal.mysite.com

the container is running fine and I can load the setup webpage.
When I insert my data to setup Docuseal  I receive this error:

![image](https://github.com/docusealco/docuseal/assets/9470145/771eb5d2-e973-4611-bdb0-b1a3165f7879)

In the log file I can see this error:

```
%I, [2023-08-10T10:45:06.784774 #1]  INFO -- : [eb048852-938c-4483-a19f-f64891a8aab0] {"method":"GET","path":"/","format":"html","controller":"DashboardController","action":"index","status":302,"duration":2.67,"view":0.0,"db":0.25,"location":"https://docuseal.mysite.com/setup","fwd":"192.168.2.1"}

I, [2023-08-10T10:45:06.903578 #1]  INFO -- : [e7dd72ab-9db1-41a2-b723-0458f928e1d8] {"method":"GET","path":"/setup","format":"html","controller":"SetupController","action":"index","status":200,"duration":11.78,"view":8.35,"db":0.24,"fwd":"192.168.2.1"}

W, [2023-08-10T10:45:13.738260 #1]  WARN -- : [da284d1f-9337-4910-a9b7-d1e23bf4f2d1] HTTP Origin header (https://docuseal.mysite.com) didn't match request.base_url (http://docuseal.mysite.com)

I, [2023-08-10T10:45:13.739229 #1]  INFO -- : [da284d1f-9337-4910-a9b7-d1e23bf4f2d1] {"method":"POST","path":"/setup","format":"turbo_stream","controller":"SetupController","action":"create","status":422,"duration":1.08,"view":0.0,"db":0.0,"fwd":"192.168.2.1"}

F, [2023-08-10T10:45:13.741258 #1] FATAL -- : [da284d1f-9337-4910-a9b7-d1e23bf4f2d1]                                                                                                                        [da284d1f-9337-4910-a9b7-d1e23bf4f2d1] ActionController::InvalidAuthenticityToken (HTTP Origin header (https://docuseal.mysite.com) didn't match request.base_url (http://docuseal.mysite.com)):
```

Do you have any suggestion to fix this issue that probably is related to the proxy setting to work with Docuseal ?

**Comment by AlexandrToorchyn** [comment]
@lucafolin Maybe this will help: [Configuring DocuSeal Behind an Existing Reverse Proxy (nginx)](https://github.com/docusealco/docuseal/wiki/Configuring-DocuSeal-Behind-an-Existing-Reverse-Proxy-(nginx))

**Comment by lucafolin** [comment]
@AlexandrToorchyn thanks for sharing, yes this is my problem but I am not able to reproduce these header rules in HAProxy.
I know this is not strictly related to Docuseal, but is it possible to deploy the same rules for HAProxy as well?

**Comment by lucafolin** [comment]
ok I solved with these setting:

![image](https://github.com/docusealco/docuseal/assets/9470145/2bb650db-0704-4526-a30a-832ffe525de7)

![image2](https://github.com/docusealco/docuseal/assets/9470145/a55f579e-3a3a-4f53-86f3-2dc460ec28e3)

thk

**Comment by AlexandrToorchyn** [comment]
@lucafolin I'm glad to hear that it's working now!
