### ISSUE TITLE
Unable to create SMTP settings

### ISSUE THREAD

**Issue by Gamechiefx** [docusealco/docuseal#93]
SSL_connect returned=1 errno=0 peeraddr=x.x.x.x:587 state=error: wrong version number

**Comment by AlexandrToorchyn** [comment]
@Gamechiefx I'm not certain, but it appears you have chosen SSL security on port 587. Ideally, port 465 should be used for SSL, and port 587 for TLS.

**Comment by alexismdr** [comment]
I'm sorry @AlexandrToorchyn but even if you check "TLS" this error is displayed. This forces me to use SSL, which doesn't help in my case. 🫤

**Comment by alexismdr** [comment]
@AlexandrToorchyn Yep!
