### ISSUE TITLE
Health check endpoint is missing

### ISSUE THREAD

**Issue by Bhautik0110** [docusealco/docuseal#96]
### Issue
- The health check endpoint should be there in order to verify the health checks of the application. It is helpful to detect unhealthy applications and prevent traffic redirect to unhealthy endpoints.

**Comment by AlexandrToorchyn** [comment]
@Bhautik0110 We're waiting for rails 7.1 which has this feature out of the box:
https://github.com/rails/rails/pull/46936

For now you can just use / path for healthcheck

**Comment by Bhautik0110** [comment]
@AlexandrToorchyn  I am new to ruby, Does rails 7.1 version mention health point checks db health status as well? Because it mentioned 
> Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.

**Comment by AlexandrToorchyn** [comment]
@Bhautik0110 Rails default healthchecker doesn't include the DB healthcheck

**Comment by Bhautik0110** [comment]
@AlexandrToorchyn If we can add the db health check, it is good when the server is unable to connect to DB (sometime we call it as readiness probe). While the default health check endpoint is used for server liveness check.

**Comment by BeshoyAtef** [comment]
used this , works fine 

`    healthcheck:
      test: ["CMD-SHELL", "netstat -an | grep 3000 > /dev/null; if [ 0 != $? ]; then exit 1; fi;"]
      interval: 60s
      retries: 100
      start_period: 20s
      timeout: 10s`

**Comment by omohokcoj** [comment]
@BeshoyAtef /up healthcheck endpoint has been added in the 1.3.6 release
