### ISSUE TITLE
Reusable Fields

### ISSUE THREAD

**Issue by robertdoneill** [docusealco/docuseal#98]
If the fields are named the same on template creation, the fields should populate the same data for the signer so they dont have to sign every field.

**Comment by AlexandrToorchyn** [comment]
@robertdoneill There is no need to create two fields with the same name - instead you can draw 2+ field areas for the same field.
![fields](https://github.com/docusealco/docuseal/assets/1176367/6eac6b69-b78c-46a3-8844-50f0afc2d5af)
